### ISSUE TITLE
Incorrect message box title in installer bash script

### ISSUE THREAD

**Issue by z1lt0id** [deadhead420/arch-linux-anywhere#1]
I was analysing your installer script (nicely done btw) and I noticed this indescrepancy.

```
if [ "$INSTALLED" == "true" ]; then
				whiptail --title "Test Message Box" --msgbox "Error root filesystem already installed at $ARCH \n Continuing to menu." 10 60
				main_menu
		else
			if (whiptail --title "Arch Linux Anywhere" --yesno "Error no filesystem mounted \n Return to drive partitioning?" 10 60) then
				prepare_drives
			else
				whiptail --title "Test Message Box" --msgbox "Error no filesystem mounted \n Continuing to menu." 10 60
				main_menu
			fi
```

Shouldn't the title parameter say "Arch Linux Anywhere" instead of "Test Message Box"?

**Comment by deadhead420** [comment]
Appreciate the heads up bro! Awesome job! You did an even better job looking over it than I did... I guess probably cause I've never even been in a situation where this menu pops up.

**Comment by z1lt0id** [comment]
no probs. its all through the code. just find and replace :)

On 3 September 2015 16:08:23 GMT+10:00, deadhead420 <notifications@github.com> wrote:
>Appreciate the heads up bro! Awesome job! You did an even better job
>looking over it than I did... I guess probably cause I've never even
>been in a situation where this menu pops up.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/deadhead420/arch-linux-anywhere/issues/1#issuecomment-137346007

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
