### ISSUE TITLE
VMware open-vm-tools needs gtkmm to work correctly

### ISSUE THREAD

**Issue by BooBerry** [deadhead420/arch-linux-anywhere#102]
https://wiki.archlinux.org/index.php/VMware/Installing_Arch_as_a_guest#Graphical_Target

Basically, open-vm-tools needs gtkmm to work correctly or else copy/paste and autosize doesn't work correctly. Tested with 2.2.4 in VMware Workstation 12.5 on Windows - it works after installing gtkmm and rebooting.

**Comment by deadhead420** [comment]
Hey man! Thanks for pointing that out! Will get the fix out soon.

**Comment by deadhead420** [comment]
Thanks again. Fix will be released tomorrow.
