### ISSUE TITLE
Mate needs gtk-engine-murrine for its theme.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#103]
I used arch-anywhere to install Archlinux with Mate in a VirtualBox machine. I noticed gtk-engine-murrine was missing as its corrupt theme display.

Adding it and then doing a logout and a login and display was right.

**Comment by deadhead420** [comment]
Is this package required? Don't see anything at all about it on the wiki.

**Comment by FredBezies** [comment]
Well... It is needed with gtk2 version of Mate. Not gtk3 one.

https://www.archlinux.org/packages/community/any/mate-themes/

> gtk-engine-murrine (optional) - for gtk2 themes
> gtk-engines (optional) - for gtk2 themes 

What about it, so ? :)

**Comment by deadhead420** [comment]
I have added it to install with mate. I have also added support for mate-gtk3 as well. This will be released in the next version tomorrow. Thanks for bringing it up

**Comment by FredBezies** [comment]
You're welcome.
