### ISSUE TITLE
Terminal output is hard to read with some terminal emulator like mate-terminal or xterm

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#104]
Output is hard to read on both mate-terminal and xterm. Just look at screenshot attached.

![terminal](https://cloud.githubusercontent.com/assets/8571419/21673761/b4127664-d32a-11e6-8bd9-d51529839cb3.png)

**Comment by deadhead420** [comment]
No offence but mate-terminal and xterm both suck pretty bad. I personally would recommend installing xfce4-terminal. Not really an issue with the installer but more just crappy emulators. You would have a much better experience with xfce4-terminal. Closing this issue. I may decide to include more fonts with mate but it generally isnt an issue when using other desktops like xfce or gnome.

**Comment by FredBezies** [comment]
Using this crappy terminal emulator for a year or so... I won't take it bad!
