### ISSUE TITLE
Adding ttf-dejavu to get a better command line display in terminal emulator.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#105]
It could be a great idea to install ttf-dejavu with xorg in order to get a readable command line. Just look at the difference between a terminal output without ttf-dejavi and one with ttf-dejavu.

![ttf-off](https://cloud.githubusercontent.com/assets/8571419/21673827/1f405f14-d32b-11e6-9eb0-cdf3a12e4b12.png)

After adding ttf-dejavu...

![ttf-on](https://cloud.githubusercontent.com/assets/8571419/21673841/347041ba-d32b-11e6-9fb5-efa21297b341.png)

Well... :)

**Comment by deadhead420** [comment]
I've added to install for all desktops. Will be releasing new version tomorrow.

**Comment by FredBezies** [comment]
Ok. Thanks for the info. Will try to report any other bugs I can find to make "2.2.5" more complete :)
