### ISSUE TITLE
Keyboard is not set to the right layout in xorg.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#106]
I can reproduce this bug easily. I asked for a french layout in installation. But in mate or in "arch-anywhere"-xfce version, it stays in qwerty layout. Annoying :(

**Comment by deadhead420** [comment]
Thank you. This should be fixed in the next release. Trying to get as much done as I can before release in a few hours

**Comment by deadhead420** [comment]
Everything should be fixed and I have pushed the changes. I'm very tired its is 05:30 here. I haven't had a chance to test anything yet so if you would like to give it a shot feel free. Best way to test is to boot into the ISO then use wget to fetch the latest script. Run this command from the ISO to update to the latest script I just released:

wget -O /usr/bin/arch-anywhere https://raw.githubusercontent.com/deadhead420/arch-linux-anywhere/master/arch-installer.sh

Shortened link:

wget -O /usr/bin/arch-anywhere goo.gl/jmnUeW

I'll be up in a few hours to start getting ready for release. Thanks again for your help!

**Comment by FredBezies** [comment]
Looks like script is broken. Adding screenshot.

![script](https://cloud.githubusercontent.com/assets/8571419/21679098/623c15f8-d342-11e6-851d-0cde9d3caca8.png)

**Comment by FredBezies** [comment]
And in xfce tweaked for arch-anywhere, keyboard is still english-US by default :(

**Comment by condor2** [comment]
Do you mean after you select keyboard layout, installer to read that layout and to type...username/user pass/root pass in that layout right?

**Comment by FredBezies** [comment]
I mean after installation. On first post-installation boot, after loading your desktop environment / window manager.

**Comment by deadhead420** [comment]
Fixed. Problem was the localectl command doesn't work in chroot. Had to create the x11 keyboard config file manually. Testing now, confident it will work.

**Comment by deadhead420** [comment]
Condor. If you get this message please respond on here..... Half the internet seems to be down, facebook, google, nothing works at all. The only sites I can visit are github, archlinux.org, arch-anywhere.org and a few others. We need to get an IRC up so we can talk.

**Comment by FredBezies** [comment]
It works. Closing bug as fixed :)

Thanks !
