### ISSUE TITLE
[wish] Adding pamac-aur in order to get a GUI tools for managing packages

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#108]
All is in the summary. Could be a great addition :)

At least to warn user about new packages.

**Comment by deadhead420** [comment]
Adding to the arch-anywhere unofficial repo. Working on a script which will update the AUR packages in my repo without me having to worry about keeping up with it. You will see this package in the next release.

**Comment by BooBerry** [comment]
Actually, would having pamac-pacaur as a choice too be possible?

**Comment by FredBezies** [comment]
Well, as far as I know, yaourt is the only wrapper officially supported.

**Comment by FredBezies** [comment]
I know about it.

**Comment by deadhead420** [comment]
Am working on a script to update and manage the arch-anywhere repo, is a bit of a pain in the ass but as soon as I have it working I'll add more packages.
