### ISSUE TITLE
Broken arch-anywhere install script in line 2033.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#111]
It is a fallback of bug #106 ; script cannot be launched, seems to be broken in line 2033.

See added screenshot.

![script](https://cloud.githubusercontent.com/assets/8571419/21679132/92d24142-d342-11e6-8fdd-ee35a534ab05.png)

**Comment by condor2** [comment]
I think I fixed :).

Try now

**Comment by FredBezies** [comment]
Indeed, fixed ! :)

Thanks !
