### ISSUE TITLE
[Mate-Desktop gtk3] gtk3-print-backends missing on installation.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#113]
Installed mate-desktop-gtk3 with "future" arch-anywhere 2.2.5 installation script, and gtk3-print-backends is not installed.

See attached screenshot. Installé = installed in french!

![print-backends](https://cloud.githubusercontent.com/assets/8571419/21682929/5984eb3c-d357-11e6-8f3a-5e72fa2bc43d.png)

**Comment by condor2** [comment]
You have chosen Mate 3 with or without extra?

**Comment by FredBezies** [comment]
Full install, so with mate-extra-gtk3.

**Comment by condor2** [comment]
added to extra. But also I can add only to Mate 3 without extra.

**Comment by FredBezies** [comment]
Ouch. Too late for me, so. I was adding some translation to french one while you made your modification.

**Comment by condor2** [comment]
I made modifications on languages 4-5 hours ago :)

**Comment by FredBezies** [comment]
No I mean for gtk3-print-backends addition.

**Comment by condor2** [comment]
ah..yes :)

**Comment by deadhead420** [comment]
This has been added to install with mate-extra
