### ISSUE TITLE
Blank window while installing Mate-Desktop. No question asked for a choice to do.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#114]
Related to bug #103 as it is related to mate installation. There is a blank window, in "Installer le bureau" (install desktop) step, where you can only answer yes or no, without knowing what the question is. 

I supposed it is related to gtk2 or gtk3 installation?

![mate-desktop](https://cloud.githubusercontent.com/assets/8571419/21683096/22dba930-d358-11e6-9516-922346210189.png)

Looks like Yes (Oui) -> gtk3 and (Non) -> gtk2.

**Comment by condor2** [comment]
because language file from ISO is diferrent from github language

run this after boot

wget -O /usr/share/arch-anywhere/lang https://raw.githubusercontent.com/deadhead420/arch-linux-anywhere/master/lang/arch-installer-french.conf

**Comment by FredBezies** [comment]
My bad. I'll try asap :/

**Comment by FredBezies** [comment]
I will try to do something about this :)

**Comment by condor2** [comment]
I made modifications on languages 4-5 hours ago :)

**Comment by deadhead420** [comment]
Yes this is in the latest translation file. The file you fetched was the main script, I added a line to the translation so to see that the translation must be downloaded too. It is asking about mate gtk3, answering yes installs with gtk3. The menu will work in the release
