### ISSUE TITLE
How can we remove  "arch-anywhere is up to date" after checking for update.

### ISSUE THREAD

**Issue by vikas-0** [deadhead420/arch-linux-anywhere#119]
After each update, I see this message " arch-anywhere is up to date"

**Comment by condor2** [comment]
From image? Or is installed on you computer?

**Comment by deadhead420** [comment]
lol hes talking about arch-anywhere custom repo. This isn't an issue, it should do that.

**Comment by deadhead420** [comment]
p.s. if you want to remove simply remove the [arch-anywhere] repo from /etc/pacman.conf

**Comment by vikas-0** [comment]
thanks. I thought its related to system name.

**Comment by deadhead420** [comment]
Might be, didn't really understand your question... In that case just change your hostname. Edit: /etc/hostname and replace with your desired hostname
