### ISSUE TITLE
[2.2.5] Swap space setup : 4096M = OK ; 4G = not enough space left.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#123]
I cloned git repository, in order to test last 2.2.5 script. Faced a big bad bug.

Simple to reproduce. When script ask you if you want swap and how much space, if you type 4096M (for example) it goes on, if you type 4G (which is the same), script warns you there is no space left on device :(

Of course, there is space left on it. I always use 128 Gb virtual HDD.

**Comment by deadhead420** [comment]
Thanks for pointing this out, was a simple error on my part, forgot to change a letter in a variable lol. This is fixed now, releasing 2.2.5 soon and will push the changes. Thanks again
