### ISSUE TITLE
Text missing for Dutch, Greek and German

### ISSUE THREAD

**Issue by speltzi** [deadhead420/arch-linux-anywhere#127]
Right at the beginning when you select the installer language. All others work fine.
Version: arch-anywhere-2.2.5-dual.iso

![virtualbox_arch_18_01_2017_15_40_56](https://cloud.githubusercontent.com/assets/24723160/22068064/119accfa-dd94-11e6-9f75-3c3f346536d5.png)

**Comment by deadhead420** [comment]
What language did you select?

**Comment by deadhead420** [comment]
Nevermind I see... Will look into it.

**Comment by condor2** [comment]
My mistake when I have updated languages for 2.2.4. Forget to close " on this line :))

keys_load="Please wait while updating pacman keyring...

**Comment by deadhead420** [comment]
Thanks for pointing out. We have fixed this but changes wont be released until I create the next ISO.
