### ISSUE TITLE
New translation!

### ISSUE THREAD

**Issue by frnogueira** [deadhead420/arch-linux-anywhere#13]
Hi!
I would like translate to Brazilian Portuguese. How I should proceed? 
Copying a conf file and renamed ?
Thanks!

**Comment by OscarHolst** [comment]
Hi, frnogueira.
It says in the beginning of each language file how you should do to translate to another language.
Copy the English one for example, translate it and send it to deadhead's email.

**Comment by frnogueira** [comment]
Thanks @OscarHolst ;)

**Comment by frnogueira** [comment]
Done @OscarHolst ! ;)

**Comment by OscarHolst** [comment]
:+1:  @frnogueira

**Comment by OscarHolst** [comment]
Since the question is answered and your translation has been merged i decide to close this issue.
