### ISSUE TITLE
Can't install with networkmanager

### ISSUE THREAD

**Issue by Ufeldraku** [deadhead420/arch-linux-anywhere#130]
If I select the networkmanager option in one of the network dialogs, it tries to install the **"network-manager-applet*$*" this makes the install fail.
Maybe related to #126 ?

**Comment by condor2** [comment]
using 2.2.5?

Work without problems

**Comment by Ufeldraku** [comment]
I selected gnome, xf86-video-ati, networkmanager, arch-base-devel, but it marks it as "network-manager-applet$" I just selected netctl.

**Comment by condor2** [comment]
Was fixed

**Comment by Ufeldraku** [comment]
Like, how?

**Comment by Ufeldraku** [comment]
So, I need to compile it, or using the iso in my usb ready to install will automatically fix itself?

**Comment by condor2** [comment]
Need to recreate ISO.

**Comment by Ufeldraku** [comment]
oh ok
