### ISSUE TITLE
version 2.2.5 does not display installer 

### ISSUE THREAD

**Issue by jonkopa** [deadhead420/arch-linux-anywhere#131]
After executing the arch install script the display font colors are off making it impossible to read the text and thus installing.

**Comment by condor2** [comment]
like this?
https://github.com/deadhead420/arch-linux-anywhere/issues/127

**Comment by deadhead420** [comment]
This should be fixed... Not really sure what you mean but I assume you mean text is not displaying in other languages. Has been fixed
