### ISSUE TITLE
Unable to boot encrypted installation

### ISSUE THREAD

**Issue by andrebrait** [deadhead420/arch-linux-anywhere#134]
I'm unable to boot after installing it. My computer won't even identify the hard disk as a bootable device.

I've booted the USB drive as UEFI and installed it as usual. I selected the option to enable UEFI boot and then used the encrypted LVM option. I selected GRUB as the bootloader. It happens with or without os-prober. Everything seems to be installed ok but it won't boot after restarting the computer.

**Comment by deadhead420** [comment]
Looking into this now

**Comment by deadhead420** [comment]
Am unable to recreate this issue in vbox or on real hardware. EFI with encryption seems to work just fine regardless of bootloader

**Comment by deadhead420** [comment]
Closing this issue for now as I am unable to recreate it... Might be an issue with your bios configuration. Please provide more info.

**Comment by andrebrait** [comment]
It's a Dell Vostro 5470 (Intel Haswell + NVIDIA Optimus laptop). I'm able to install pretty much any distro with LUKS+LVM but Arch using Arch-Anywhere. I'm installing it on a SanDisk SSD Plus G25 (480GB).

I have tested: 

Ubuntu/derivatives 16.04 and 16.10
Manjaro 16.10.3
Antergos (2017.1 Snapshot)
Fedora 24 and 25

Doesn't seem to be an issue with my laptop's firmware, sibce it works with pretty much any distro/installer but Arch-Anywhere. All distros tested with grub. It doesn't even detect the disk as a bootable storage unit after using Arch-Anywhere.

**Comment by andrebrait** [comment]
Also tested Solus and OpenSUSE and both worked ok, too.

**Comment by andrebrait** [comment]
Debian 8.6, 8.7 and testing (RC1) too.

I have tested lots of distros lately. I was looking if I could be satisfied with something other than Arch (and the answer was 'nope').

**Comment by emilburzo** [comment]
@andrebrait did you ever find a solution? just ran into this myself... also with a dell.

**Comment by marek287** [comment]
I Have same problem with HP.
BootDevice Not Found
