### ISSUE TITLE
Request: installer with LTS kernel

### ISSUE THREAD

**Issue by dragynbane222** [deadhead420/arch-linux-anywhere#136]
So my hardware, for whatever reason my system hangs on the 4.8 and 4.9 series of the kernels of most distros, Arch included, (still trying to pin what happens, dmesg is usually useless for this as the system stops writing to dmesg before it hangs). I can get by with linux-lts, but arch-anywhere cannot be used by me without linux-lts baked into the installer, since Arch uses one of the problematic kernels when it comes to the CPU I have (this didn't happen on my old FX-4100, only started happening with my FX-6300). and arch-anywhere seems to use whatever version the linux package is when the ISO is built (which from what I recall was 4.8.x as of the last ISO). I have the feeling I'm not the only one who runs into this issue.

I would have marked this with the proper label if I knew how, lol, most I know about github is gists, bug reports and actually working on code.

**Comment by condor2** [comment]
You chosed LTS when install?

**Comment by deadhead420** [comment]
What exactly is the issue? Arch anywhere includes an option for lts kernel...

**Comment by deadhead420** [comment]
Closing this issue since the installer already has an option for LTS

**Comment by dragynbane222** [comment]
Sorry, I didn't have time to reply before now, but the issue isn't that the installer doesn't have an option to install the lts kernel, but rather that there isn't a iso with said kernel in it, without said kernel, I randomly get a hang, and should said hang happen during installation, I have to reboot the system (and my CMOS acts as if it had been reset, so not sure what the issue is), and as with how root seems to need to be formatted each time I run the installer, I can never get to the point where even the kernel is installed, so no complete and bootable system is up before the hang occurs.
