### ISSUE TITLE
Grub don't use the defined keymap

### ISSUE THREAD

**Issue by kadogo** [deadhead420/arch-linux-anywhere#142]
Hi,
Exemple if you conigure a passphrase for lvm you fall on a grub that use qwerty input in place of your personal keymap.

To repair that, you need to add "keymap" before encrypt (example) in mkininitcpio.conf in HOOKS section.

I would make a PR but I don't know how you want handle it.

**Comment by pnedkov** [comment]
#148 

Please, let me know if that fix works for you.

**Comment by kadogo** [comment]
It's strange, the file is well modified but it was not applied.
I need to do manually mkinitcpio -p linux so that it work.

**Comment by pnedkov** [comment]
It is indeed strange. We run "mkinitcpio -p linux" on the line after.
It looks like the order in HOOKS is significant. Could you please try "keymap encrypt lvm2 block filesystems" instead of "block lvm2 keymap encrypt filesystems"? Just a wild guess.

**Comment by deadhead420** [comment]
keymap has been added to hooks line.... Not sure if this has been fixed or not?

**Comment by deadhead420** [comment]
This should be fixed now, closing issue. Please re-open if the issue persists.
