### ISSUE TITLE
 PulseAudio is needed to play sounds in Mate installation.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#144]
Hello.

Just look at the title. It sums up the problem.

**Comment by condor2** [comment]
You can find pulseaudio at the end of installer. Software category, audio.

**Comment by FredBezies** [comment]
I know, but... No pulseaudio == no sound in Mate. That's this simple.

**Comment by condor2** [comment]
Added as default pulseaudio, pulseaudio-alsa, alsa-utils

**Comment by FredBezies** [comment]
Working now! Too bad arch-anywhere repository is down this morning! :(
