### ISSUE TITLE
[2.2.5] Manual partitioning doesn't start when using french locale?

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#145]
Simple bug to reproduce. Try to launch arch-anywhere in virtualbox. Select another language than english.. And try to run custom partition setup...

You get this error message, related to missing space on HDD... And of course, it works at least with english  german, dutch, indenosian versions of the installer :(

What is broken?

![001](https://cloud.githubusercontent.com/assets/8571419/22780272/6a0e8f8a-eebe-11e6-8884-84412d9abf85.png)

**Comment by FredBezies** [comment]
I tried again with git... Same bug. Only in french... What's going on?

**Comment by FredBezies** [comment]
Here is a video showing the bug. French speaking install -> bug ; english speaking install -> OK.

https://framadrop.org/r/oIIDENv759#fqt5p5BhCGzgXbK+6/7/sskLQTl6UF3Ri5t2eK3IcPM=

**Comment by condor2** [comment]
Isn`t language bug. 99% I think is manual script bug, because on german,romanian languages show wrong....hdd size should be 14,8GB and not 148GB

English use " **.** " and romanian, german " **,** "

**Comment by pnedkov** [comment]
I spent some time on this and there are more than one problems

1. I fixed the displayed size by changing:
`dev_size=$(fdisk -l | grep -w "$device" | awk '{print $3$4}' | sed 's/,//')`
to this:
`dev_size=$(fdisk -l | grep -w "$device" | awk '{print $3$4}' | sed 's/,$//')`


2. Eventually I changed it to
`s/,$//;s/,/./`
in order to work with "." instead of ","

But then I hit the biggest problem:

3.

![fdik_device](https://cloud.githubusercontent.com/assets/6212427/22859358/be2094d0-f08d-11e6-9edf-3d404a089d09.png)


If we change the language other than English there is no way this would work:

`sed 's/Disk //;s/://'`

**Comment by pnedkov** [comment]
#149 

It seems to be working. I cannot fully test it since from the supported languages English is the only language I know. Please let me know if there are any issues.

**Comment by condor2** [comment]
Great job @pnedkov . Now show correctly hard drive size. Same error on French...but I will check the language file because when change locale from english file to french it work.
![screenshot_20170212_094150](https://cloud.githubusercontent.com/assets/14251939/22860475/c492e460-f107-11e6-9b4a-34bee9a524c4.png)

**Comment by FredBezies** [comment]
@condor2 creating a new iso from git.. Testing it. And you're screenshot is speaking german, or am I wrong?

**Comment by condor2** [comment]
Is screenshot is german to see if show size cortectly.

And for french is the first error...possible because of this line....
[code]
		if [ -z "$ROOT" ]; then
			case "$part_size" in
				[4-9]G|[0-9][0-9]*G|[4-9].*G|T)[/code]

**Comment by FredBezies** [comment]
Ok. By the way, can you merge the last french translation I proposed? It fixes some mistakes and remove non existing french words?

Thanks!

**Comment by condor2** [comment]
I don`t see any pull request :)

**Comment by FredBezies** [comment]
Oh...

Well, I will update french translation now!

**Comment by condor2** [comment]
In french language you use same english comma?? "  ,  "

**Comment by FredBezies** [comment]
https://github.com/deadhead420/arch-linux-anywhere/pull/150

Comma for what use?

**Comment by condor2** [comment]
when write in french

**Comment by FredBezies** [comment]
We use it, yes. Of course  :)

**Comment by condor2** [comment]
same in romanian...and script work :)

**Comment by FredBezies** [comment]
This is unfair! Why? :(

**Comment by condor2** [comment]
Aliens :)
I will verify again language...if not i will rewrite entire language :))

**Comment by FredBezies** [comment]
Please not... :(

I don't understand why root_err_msg is "called" everytime :(

**Comment by pnedkov** [comment]
Found the problem.

Executing "bash part.sh" throws the following error:
Can't make new window at (1,-1), size (21,80)

I opened the part.sh script and removed the word "changements" from the --extra-label and it works! I guess the string is just too long. Please, whoever spoeaks french to fix the translation accordingly.

**Comment by condor2** [comment]
Hmm..I will try to increase size of window...to see if work :)

**Comment by FredBezies** [comment]
@pnedkov which chain to shorten?

**Comment by pnedkov** [comment]
@FredBezies, I changed this:
`write="Appliquer les changements"`
to this:
`write="Appliquer les"`

And the menu started working.

@condor2 , not sure if this is possible. The virtualbox window is 24x80.

**Comment by FredBezies** [comment]
@pnedkov working on it. Providing change asap. Thanks for the tip!

**Comment by condor2** [comment]
Hmm that line was the same problem  at my language long time ago and I translated like this

`write="Write-changes"`

**Comment by FredBezies** [comment]
Fix? https://github.com/deadhead420/arch-linux-anywhere/pull/151

Replaced write="Appliquer les changements" with write="Enregistrer" (to save)

Hope it works...

**Comment by pnedkov** [comment]
It works. Just tested it. Thanks!

**Comment by FredBezies** [comment]
@pnedkov : I need to see it run :)

It will maybe some more tweaking, but it if launches...

**Comment by FredBezies** [comment]
I will look at this part. And modify translation file. It will took about 30 minutes. But at I least, I can access to custom partition setup... :D

**Comment by pnedkov** [comment]
@FredBezies , what does the cfdisk say in English?

**Comment by FredBezies** [comment]
Will tell you asap! Let me boot a new iso.

**Comment by pnedkov** [comment]
@FredBezies , just take a look at the attached screenshot by @condor2

**Comment by FredBezies** [comment]
Modified my comment :)

**Comment by pnedkov** [comment]
This is ridiculous. Thanks for the translation.

**Comment by FredBezies** [comment]
Even shortening changes, still cfdisk error... What the?

**Comment by pnedkov** [comment]
Found the problem. Working on it. It is in the code, not in the translation.

**Comment by FredBezies** [comment]
Far too long translation for cfdisk. It warns you changes are not taken into account, or something like this. As message is truncated... :(

By the way, I shorten translation for manual_part_var3. Will commit it asap. Message won't be cut this time :)

**Comment by pnedkov** [comment]
#153 

This should fix it. I do not know where this characters are coming from but I got rid of them once and for all!

![partition_whitespace](https://cloud.githubusercontent.com/assets/6212427/22861092/015ea89a-f0c5-11e6-8a6f-15b01a9cdb11.png)

**Comment by FredBezies** [comment]
Will try it. Reporting asap!

**Comment by pnedkov** [comment]
Using the French translation I can reach cfdisk with no problem. From this point on it is all yours.

**Comment by FredBezies** [comment]
Added some tweaks. Now this pita bug can be closed :)

**Comment by condor2** [comment]
Test if you can create swap....

**Comment by FredBezies** [comment]
I will test this asap.

**Comment by condor2** [comment]
Should ask and auto activate swap...but no. It ask to select a mount point..
![screenshot_20170212_125859](https://cloud.githubusercontent.com/assets/14251939/22861509/082d2490-f123-11e6-88e1-81d17c65a78c.png)

**Comment by FredBezies** [comment]
Ouch :(

And not in english speaking version, I suppose?

**Comment by condor2** [comment]
Possible because of this:

`if [ "$part_type" == "Linux swap" ]; then`

and script try to read: Linux swap...but in french is `partitcion d'enchance`

Maybe @pnedkov can fix this issue :D

**Comment by FredBezies** [comment]
Another script issue ? I was trying to see if it was a translation bug... Well... :)

**Comment by condor2** [comment]
No isn`t translation bug, because if you ran this in english:
`fdisk -l | grep "$(<<<"$device" sed 's/^..//')" | awk '{print $7,$8}'`
you will see something like this:

Id Type
Linux swap

and in french is

Id Type
partition d'echange  = Linux swap

and script read this
`if [ "$part_type" == "Linux swap" ]; then`

**Comment by pnedkov** [comment]
#157 

I had to rework the whole section where part_type gets set. Now the code handles properly MBP and GPT partition tables and also it is language agnostic. Please give it a try and share your thoughts.

**Comment by condor2** [comment]
Tks @pnedkov .

Tested but same SWAP 
![screenshot_20170212_230311](https://cloud.githubusercontent.com/assets/14251939/22866011/827eebbc-f177-11e6-8004-7807324cf5be.png)
![screenshot_20170212_230337](https://cloud.githubusercontent.com/assets/14251939/22866013/858d230a-f177-11e6-8736-680a05d9d29e.png)

problem when use french. When you select swap ask you to select a mount point and not ask to format and enable swap like in english.

**Comment by FredBezies** [comment]
Sigh. No need for me to test this patch, so... Why so much _"""hate"""_ for french version?

**Comment by pnedkov** [comment]
#159 

Every time we grep for a English word is wrong. How about now?

**Comment by condor2** [comment]
same problem....

And yes, I think it should be in english cfdisk...

**Comment by FredBezies** [comment]
Indeed. Translation of cfdisk are sometimes weird or hard to understand when you're used to the english speaking version.

**Comment by FredBezies** [comment]
> And yes, I think it should be cfdisk only in english to pass this bug..

Let's hope so... I'm fed up with this bug.

**Comment by pnedkov** [comment]
Just getting rid of the LANG variable from the language files will make our lives easier. Once this is done the choice is whether or not to run cfdisk with LANG in front of it in order to get the same language as in the dialogs. Not sure what is more ugly - having the dialogs in one language and cfdisk in English or having everything in a language other than English.

**Comment by pnedkov** [comment]
#151 

Two more regex fixed. Please give it a try.
There are a bunch of `grep "EFI"`. I hope I do not have to fix them.

**Comment by FredBezies** [comment]
Nothing changed for me. Will try adding LANG=en_US.UTF-8 right before cfdisk lines.

Will try to see if something is changed with that. Sigh...

**Comment by condor2** [comment]
Weird now swap not working in romanian, and cfdisk isn`t translated in romanian, is in english :)

**Comment by FredBezies** [comment]
Ouch! Looks like I opened Pandora's box when I filled this bug...

Can it be more broken?

**Comment by pnedkov** [comment]
Just a quick question: Have i broken any functionality in the installer when English language is selected? If not, this is a very good sign. We are just dealing with several different problems and we are fixing them one at a time. We are getting there. I am positive. My real problems are finding time to address all the issues and navigating through a non-English installer.

**Comment by condor2** [comment]
Yes, now english has the same SWAP problem like french :)

**Comment by pnedkov** [comment]
@condor2 , please give me a chance to fix it. If it is reproducible with English it should be easy.

**Comment by condor2** [comment]
ok :)

**Comment by pnedkov** [comment]
#162 

Stupid mistake. Sorry about that.

**Comment by pnedkov** [comment]
#163 
I just fixed all the languages that use decimal comma.

**Comment by pnedkov** [comment]
Phew! Let's see what @FredBezies has to say after these two fixes. 

The root cause of the problem was fundamental. Now all regular expressions are language agnostic and the code properly handles the different decimal marks. We should not face issues like this in the future except when the translated word/sentence is too long and can't fit. We do not have safety net for such cases.

**Comment by FredBezies** [comment]
Generating ISO. Will report and edit this post asap. First for bios, then for EFI.

Keeping fingers crossed :D

**Comment by pnedkov** [comment]
@FredBezies you do not have to generate the iso. Follow the steps here: #143

**Comment by FredBezies** [comment]
Thanks for the tip. But I think it is better to start with a fresh ISO. At least, I will have the full experience :)

**Comment by deadhead420** [comment]
Hey guys I'm here. What do we need to fix? lol

**Comment by deadhead420** [comment]
About to make some major updates, I added a shell function library I'm about to test for the first time

**Comment by FredBezies** [comment]
@deadhead420 very funny :P 

By the way, swap formatting seems to work now... Keeping fingers crossed until I tested both EFI and bios mode.

**Comment by deadhead420** [comment]
Sounds good! Thanks man! I'm going to do some tests then get ready to release 2.2.6

**Comment by FredBezies** [comment]
Well, there is another blocker I think... Bug https://github.com/deadhead420/arch-linux-anywhere/issues/164
