### ISSUE TITLE
[2.2.5] LXQt installation cannot be made. Wrong or unknown GPG key?

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#146]
Hello.

I tried to install LXQt and installation doesn't work. Looking at arch-anywhere.log, it looks like it is related to an unknown or missing GPG key from Jerome Leclanche.

![002](https://cloud.githubusercontent.com/assets/8571419/22780831/6229ee52-eec0-11e6-8421-bc6a2d0cb4a8.png)

**Comment by pnedkov** [comment]
Boot from Arch Anywhere or Arch Linux iso with the "cow_spacesize=1G" boot option. And then:

pacman -Sy
pacman -S git
git clone https://github.com/deadhead420/arch-linux-anywhere.git
cd arch-linux-anywhere/
./arch-installer.sh

**Comment by FredBezies** [comment]
Well, looks like 2.2.6 will fix this bug. Thanks for the info. I'll try to find why I cannot run custom disk partitioning with french locale now.
