### ISSUE TITLE
Multimedia category cannot be opened.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#155]
Tried on last git version. When you're in "Install software" step, you cannot enter Multimedia category. Other categories can be managed. There is an error but I cannot read it :(

**Comment by condor2** [comment]
In french? Testing now

**Comment by FredBezies** [comment]
No. Both in french and english. I verified before opening this issue!

**Comment by condor2** [comment]
Fixed.

Some stupid spaces :)

**Comment by FredBezies** [comment]
Another bug the dust. Now, waiting for the last (??) fix related to custom disk setup bug.
