### ISSUE TITLE
Multimedia-codecs cannot be added?

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#164]
Looks like there is a bug when you try to add multimedia codecs from multimedia category.

It breaks additional software installation. Can't see error message. Maybe a spelling in packages?

**Comment by deadhead420** [comment]
Looks like that package is not in the official repos... Not sure why it was added...

**Comment by deadhead420** [comment]
Nevermind I see the problem now, fixing

**Comment by deadhead420** [comment]
Should be fixed now

**Comment by deadhead420** [comment]
@FredBezies it seems some users are having a problem installing deepin desktop. testing now

**Comment by FredBezies** [comment]
@deadhead420 will test multimedia-codecs fix asap and report. Deepin ? As it is speaking - for some times? - only chinese and english, I didn't test it.

**Comment by deadhead420** [comment]
I think its an issue with outdated keys. Need to update ISO asap

**Comment by FredBezies** [comment]
By the way, there is a problem with multimedia-codecs fix. Used Archlinux and tweak from bug #143, and I get 2 errors lines blocking arch-installer startup.

![error](https://cloud.githubusercontent.com/assets/8571419/22950599/7681616a-f306-11e6-8906-b7da010e65c3.png)

Deepin? Will look at packages and see if there is more translation or not.

**Comment by FredBezies** [comment]
Just add " before ) in line 2079 to fix startup bug.

**Comment by deadhead420** [comment]
Thanks man just fixed missing quote

**Comment by FredBezies** [comment]
You're welcome. Very annoying bug, indeed. Testing codecs installation asap and report.

**Comment by deadhead420** [comment]
Sounds good!

**Comment by FredBezies** [comment]
Well. Something is still broken. If I select multimedia codecs to add them, it asks me if I want to skip adding software from multimedia category... Translation bug?!

**Comment by deadhead420** [comment]
Hmmm strange. What language?

**Comment by FredBezies** [comment]
French, as usual. Will try to see if it happens also in english.

**Comment by condor2** [comment]
Work in english :)

**Comment by FredBezies** [comment]
Well, will try to modify again translations...

**Comment by deadhead420** [comment]
Only way that can happen is if cancel button is pressed

**Comment by FredBezies** [comment]
I didn't remember I pressed cancel before. Will try again asap.

**Comment by deadhead420** [comment]
Sounds good. I'm updating my local repo then I can do some testing too

**Comment by condor2** [comment]
@FredBezies if you want more tweaks for you language you can do like mine.

If you want to translate backtitle...

dialog_msg() {

title=" -| Arch Linux Anywhere |- "

backtitle=" -| Arch Anywhere - Instalator Arch Linux |- "
}

If you want to translate software descriptions...

### Multimedia
media0="Conversie video-DVD"
media1="MPlayer"
media2="Editor video"
media3="Captură video"

**Comment by FredBezies** [comment]
At least, adding these translations :)

**Comment by FredBezies** [comment]
Will look at these modifications. Will tweak some little things I saw while doing some testing.

**Comment by FredBezies** [comment]
I will try to reproduce this bug in a few hours. It is 00:03 where I live. I need to sleep. Be back in about 10 hours for some bug testing.
