### ISSUE TITLE
Another additional software install bug : calligra-sheets cannot be added?

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#169]
Hello.

I wanted to test Plasma installation (worked OK), and I wanted to add Calligra as default office software.

As calligra sheets doesn't exist anymore it breaks installation telling user there is 0 Mb to download. Ouch!

Here is the output of pacman -Ss calligra : 

```
fred@fredo-arch ~ % pacman -Ss calligra
extra/calligra 3.0.0.1-5
    A set of applications for productivity and creative usage
extra/kexi 3.0.0-2 (calligra)
    A visual database applications creator
```

**Comment by condor2** [comment]
You have selected both packages: calligra and calligra-sheets?

**Comment by FredBezies** [comment]
@condor2 on my first try yes. So it blocked. I looked at pacman package list and noticed calligra-sheets was not existing anymore.

Removing dead entry in order to prevent such a bug is a good idea.

**Comment by condor2** [comment]
Removed calligra-sheet and added language support for calligra. Should work :)

**Comment by FredBezies** [comment]
Fixed indeed. Thanks!
