### ISSUE TITLE
Firefox and Thunderbird translations are not installed with firefox and thunderbird packages.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#171]
Hello.

I used latest arch-anywhere git version, and I noticed if I installed Arch-Anywhere in french there is no translation package added for Mozilla Firefox. It is the same for Thunderbird.

To be clear : firefox-i18n-xx (language code) should be installed with firefox package and thunderbird-i18n-xx for thunderbird.

Looks like bug #107 which was related to LibreOffice package.

**Comment by deadhead420** [comment]
Hey man. Just updated the script. It should now install language package when installing firefox or thunderbird. Haven't tested yet but I'm sure it will work, I have it setup just the same as I did for libreoffice. Feel free to test it out if you get a chance. Thanks for pointing that out, I normally don't test any of the translations so never notice stuff like this. Leaving issue open until I'm sure its working good - thanks again.

**Comment by FredBezies** [comment]
Well. It doesn't seem to work. Asking to add firefox... And only firefox is added. See attached screenshot.

And of course, I used an up to date git version. What's going on ?

![french-missing](https://cloud.githubusercontent.com/assets/8571419/23092369/7973e1c0-f5c9-11e6-98dc-080b1c93de34.png)

Maybe @condor2 can verify my problem here?

**Comment by FredBezies** [comment]
Guess what... I can get french translation to be selected by modifying line 51 (for french) : 

"French") export lang_file="$aa_dir"/lang/arch-installer-french.conf lib=fr bro="$lib" ;;

Replaced by : 

"French") export lang_file="$aa_dir"/lang/arch-installer-french.conf lib=fr bro="fr" ;;

Looks like installer doesn't like at all bro="$lib"... I found this by looking at Swedish line. Looks like you'll have to modify every single bro="$lib" by bro="country-code"

Just an educated guess, of course :)

**Comment by condor2** [comment]
I fixed firefox and thunderbird translations :)
I don`t know if is a PRO solution but it work :D

**Comment by FredBezies** [comment]
Will try it asap. Not the best solution, but at least it works :)

Let's hope @deadhead420 won't get angry about these modifications :D

**Comment by condor2** [comment]
Neah :))

**Comment by FredBezies** [comment]
:D 

By the way, the only missing translation will be for kde. It uses kde-l10n-country code name. Maybe I have to open another bug for this issue?

**Comment by condor2** [comment]
kde translation?

**Comment by FredBezies** [comment]
Yes. I noticed there were not installed with kde, either minimal or full installation.

**Comment by condor2** [comment]
I think is for kde apps and not for kde translation. I will test.

**Comment by FredBezies** [comment]
Correct me if I'm wrong, but without translation package, some "base" applications like dolphin are not fully translated. I'll need to verify this anyway.

**Comment by condor2** [comment]
Possible....test now...

**Comment by condor2** [comment]
Added code...but work only with plasma minimal...
Need to find another way...I am not good in bash =))

**Comment by FredBezies** [comment]
I think @deadhead420 will find something better :)

Or let's hope so :)

**Comment by condor2** [comment]
Is a noob bash code :)).....but you can test.
Maybe @deadhead420 will tune that code :gear:

**Comment by deadhead420** [comment]
Looks like everything is working good. Closing issue - thanks guys!

**Comment by FredBezies** [comment]
You're welcome :)
