### ISSUE TITLE
Missing packages for Budgie Desktop.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#176]
You can add : 

- arc-icon-theme
- arc-gtk-theme
- elementary-icon-theme (as fallback theme for arc-icon-theme package)

It will help make Budgie more "pretty" ;)

**Comment by deadhead420** [comment]
Added when installing full budgie desktop (not minimal)

**Comment by FredBezies** [comment]
Thanks!
