### ISSUE TITLE
VMware Tools and related stuff

### ISSUE THREAD

**Issue by smersh2** [deadhead420/arch-linux-anywhere#178]
Ok, I am testing as of now how VMware tools works with Arch Anywhere v. 2.2.6.
1. So far there is an issue with Gnome gdm (lightdm looks loke works fine)
2. When trying Cinnamon, I was not able to decompress *.tar.gz files (everything was ok under Gnome). Please add when choosing Cinnamon following line to installation script - #pacman -S file-roller p7zip zip unzip unrar
Thanks

**Comment by deadhead420** [comment]
Added these packages to cinnamon and unzip is now installed by default for every DE.

**Comment by smersh2** [comment]
Openbox branch is useless - after install nothing works. Openbox may be taken out from install script choices
https://www.facebook.com/groups/1648126935492037/permalink/1648836412087756/
