### ISSUE TITLE
Cinnamon installation : gnome-terminal is "mandatory".

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#182]
Hello.

I've done a Cinnamon installation and noticed gnome-terminal was not installed. It is "mandatory" if you want a terminal emulator in Cinnamon start menu.

Can it be added? Thanks.

**Comment by deadhead420** [comment]
Not a problem, just added it to be installed with cinnamon.

**Comment by FredBezies** [comment]
Thanks a lot! :D
