### ISSUE TITLE
Intel microcode Fails to install correctly

### ISSUE THREAD

**Issue by CyberManifest** [deadhead420/arch-linux-anywhere#183]
<img width="721" alt="screen shot 2017-02-20 at 2 50 40 pm" src="https://cloud.githubusercontent.com/assets/22405699/23144412/3a987dee-f77c-11e6-8db7-992b29450d71.png">
The intel microcode as described here: 
https://wiki.archlinux.org/index.php/Installation_guide#Boot_loader

> If you have an Intel CPU, install the intel-ucode package in addition, and enable microcode updates.

... does not install correctly in Arch-Anywhere  2.2.5

As a work around:  
Intel microcode has to be installed manually with "pacman -S intel-ucode" from Chroot after install.

**Comment by deadhead420** [comment]
Fixed. I've removed ucode from base install and install it in chroot after, I've also removed ucode entirely when using a vm

**Comment by FredBezies** [comment]
Seeing it today while testing 2.2.7-git version :(

![capture du 2017-03-15 08-37-43](https://cloud.githubusercontent.com/assets/8571419/23938563/200e834a-095d-11e7-89e5-379cb5a9997a.png)

Does this bug need to be reopened ?

**Comment by deadhead420** [comment]
@FredBezies no. I'm not really sure why but this happens every single time in vbox. Doesn't make much sense and I have no clue how to get rid of it. Happens no matter what cpu you have AMD or Intel. I don't think it has anything to do with intel-ucode. I've looked into it a bit but can't seem to find any solution, or any way to supress the error... It doesn't cause anything to happen, the system will still start just fine so it presents no issue. Nonetheless its still very annoying, I would like to figure out a way to hide it but haven't been able to as of yet.

**Comment by FredBezies** [comment]
I understand. But at least a release note to say : don't be worry, this is an harmless warning.

What about it?

**Comment by deadhead420** [comment]
I could do that... I would really like to get rid of it all together just haven't figured out how yet
