### ISSUE TITLE
Xchat Src/Target Broke

### ISSUE THREAD

**Issue by CyberManifest** [deadhead420/arch-linux-anywhere#184]
Error Trying to add XChat to install. See attached Image.
![virtualbox_arch linux virtual machine_20_02_2017_15_03_47](https://cloud.githubusercontent.com/assets/22405699/23144677/1e1ab16c-f77e-11e6-9697-90e373341cfc.png)

**Comment by condor2** [comment]
Was fixed for next release :)

https://github.com/deadhead420/arch-linux-anywhere/issues/174
