### ISSUE TITLE
Fail to boot after Install

### ISSUE THREAD

**Issue by CyberManifest** [deadhead420/arch-linux-anywhere#185]
Arch-Anywhere Fails to recognize any boot medium after install....

![virtualbox_arch linux virtual machine_20_02_2017_15_32_48](https://cloud.githubusercontent.com/assets/22405699/23145311/41ff7af0-f782-11e6-96c6-b04e06f568e3.png)
![virtualbox_arch linux virtual machine_20_02_2017_15_33_23](https://cloud.githubusercontent.com/assets/22405699/23145312/42016a7c-f782-11e6-9194-93f17bc62d2a.png)
![virtualbox_arch linux virtual machine_20_02_2017_15_34_00](https://cloud.githubusercontent.com/assets/22405699/23145310/41ff26b8-f782-11e6-8206-07f8b909b4e1.png)

Saw a few errors along the process... just watch:
https://mega.nz/#!3Is0DQxb!liZveoxTdAFx5NSOPZt73s5zYQVDJZoAyWC5NGw8drE
or
https://drive.google.com/open?id=0BxQBblWyreFDS1FzSmxocVdZcTA

**Comment by condor2** [comment]
what version?

**Comment by CyberManifest** [comment]
2.2.5

**Comment by deadhead420** [comment]
Any more info on the type of install you did. For example was it normal linux kernel, lts kernel, or grsec kernel. Did you use encryption, what filesystem type did you use?

**Comment by deadhead420** [comment]
Closing issue, resolved on facebook. Used did not create BIOS boot partition when using GPT autopartition with legacy bios
