### ISSUE TITLE
Grub install on UEFI fails if $ESP mountpoint is other than /boot

### ISSUE THREAD

**Issue by jscholfield** [deadhead420/arch-linux-anywhere#19]
On the line installing grub for UEFI, the mount point is hard coded to /boot instead of pulling in any custom mount point chosen, such as /boot/efi. I have an existing Arch instance that uses /boot as it's mount point for the $ESP. If I used the same for Arch-anywhere, that kernel would overwrite the kernels files of my other instance. 

This causes the grub-install command to fail. That means the corresponding entry doesn't get written to the UEFI variables and at least some of the grub files don't get written to the $ESP. The grub-mkconfig does create the grub configuration file.

From line 1234-
  ### Chroot into system and install grub with efi options enabled
  ### Rename the grubx64.efi boot file
					arch-chroot "$ARCH" grub-install --efi-directory=/boot --target=x86_64-efi --bootloader-id=boot &> /dev/null &
					pid=$! pri=0.5 msg="\n$grub_load1" load
					mv "$ARCH"/boot/EFI/boot/grubx64.efi "$ARCH"/boot/EFI/boot/bootx64.efi

There are a few places in this where the file paths are incorrect if /boot is not the $ESP.

There is also a typo I believe. /boot/efi/EFI/boot should be /boot/efi/EFI/Boot. /boot/efi/EFI/boot doesn't exist for me at least.

I'm willing to try and fix this if you'd like but I haven't completely worked out doing that just yet.

**Comment by jscholfield** [comment]
I didn't intend to close this issue, just the comment I had started. So I have re-opened the issue. I have found this to not be as easy as I had hoped to fix, not easy for me at least. I have also found that opinions seem to have changed some about using mount points other than /boot for the ESP. 

I'm a linux user, an Arch Linux user and for this use case an Arch Linux user with multiple Arch Linux instances installed on one physical machine so I accept than my use case might be just a bit off the beaten track.

Because of that I know that changing this may not be of the highest priority but it does seem to me it should be addressed. If I had chosen one of mount points offered, not used the custom option offered, my kernel files for my other Arch Linux instance would have been overwritten. I could have worked that out but there would have been pain involved.

I see using /boot/efi isn't very well discussed in the wiki. I think that with VM use much higher now it makes my use case even odder. I have some thinking to do. But, no matter, I think this still does have to be fixed since my odd use is the most common use of the custom mount point option, using it for the ESP.

I think I see the mount point of the ESP being captured in a variable BOOT for later use. Is that correct? I think that happens for all use cases of an ESP being created and/or mounted (maybe also for a /boot partition on an mbr system).

If I do understand this correctly the fix may be as simple as changing line 1236 (shown above) to use $BOOT instead of the hard coded /boot. That does however leave this same issue in other places unless I attack them too. 

I believe the --bootloader-id= parameter on that same line creates a directory and boot for that directory name is potentially confusing in an already convoluted directory path on the ESP. I use the same word on that parameter as I use for my hostname on that installed instance of Arch. It also labels the new entry in the UEFI boot entry. Here is the description in the arch wiki.

```
The --bootloader-id is what appears in the boot options to identify the GRUB EFI boot option; make sure this is something you will recognize later. The install will create a directory of the same name under $esp/EFI/ where the EFI binary bootloader will be placed.
```
To end this long comment before it gets any more confusing I'll say that I don't consider this to be a trivial fix, as I honestly hoped it would be. For the experience I will still try to work on this fix unless you tell me to leave it to you or someone else. If I'm on the wrong track and anyone wants to help me onto the right track I'd gladly accept that.

I see such things such as changing the directory name and UEFI boot entry label as separate issues that I will propose.

**Comment by deadhead420** [comment]
I do get what you're saying and have looked into this some but have been too busy to get anywhere with it. It took me forever to actually get uefi boot working. I sort of just rigged it all together and got it working somehow. As far as I know grub requires things to be setup the way I have them but again I'm not an expert in efi and find the entire topic to be very confusing. It took me months to even get it working in arch anywhere so I know that working on it is always a big project. I will look into this more later when I have time and already have some ideas of how to make it work (selecting custom mountpoint for esp) but it will require lots of testing and a greater understanding on my part of how the entire efi boot process works.

**Comment by jscholfield** [comment]
I understand. I may not fully understand much it seems but UEFI boot and how it works with Arch Linux is something I do have a pretty good handle on. I know that may sound crazy but I've seen and worked through lots of issues caused by both installers and myself.

This is an issue that will be coming up as more people use this. Forgive me if this is something you already know but I'd like to explain why a capability of using a mount point of /boot/efi is necessary. My example isn't the only example but it is a clear one.

I have Arch installed already as my only OS/distro. With only one boot option I configured for no boot loader, I have UEFI launch the kernel directly. I use efibootmgr to create the boot entry that does that. Choosing /boot as the mountpoint for my ESP puts the kernel on the ESP itself, not on my Arch root partition.

If I were to use /boot as the mountpoint for another distro or Arch installer such as yours that uses the same kernel names as Arch, the kernel would be overwritten. If I use /boot/efi the new kernel gets written to the root partition of the new distro and nothing is in conflict. 

I can work around this but most can't and could bork their systems in ways that can be recovered from but still might well lead to lost data and lead them to get pretty pissed. Anyway, I have been busy lately but will try to find enough time to think more about this. I'm happy to help in any way I can so I'll try to keep an eye open for how this is going at the least.

**Comment by deadhead420** [comment]
Just did some tests and I've got it working. You can now use /boot/efi. Doing some more testing but it seems to be working perfect. Sorry for the slow response on this issue. I had to figure out the best way of doing this and it turned out to be pretty easy. 

Just finished a full install. Selected custom mountpoint - set as /boot/efi. Continued install. System booted right up with no issues. Closing this issue and will release the fix very soon. Please feel free to test it out and let me know if you run into any issues!
