### ISSUE TITLE
failed to set up Using UEFI

### ISSUE THREAD

**Issue by jiaxin96** [deadhead420/arch-linux-anywhere#200]
error message

Mounting /run/archiso/cowspace (tmpfs) filesystem, size=256M...
losetup: /run/archiso/bootmnt/arch/x86_64/airootfs.sfs: failed to setup loop device: No such file or directory

**Comment by condor2** [comment]
what version?

**Comment by deadhead420** [comment]
This is another issue identical to #196 has already been fixed just waiting to do the new release.

**Comment by jiaxin96** [comment]
the version is ARCH_201702.
thanks for your job @deadhead420

**Comment by deadhead420** [comment]
No problem! Will be releasing version 2.2.7 in three days and this issue will be fixed.
