### ISSUE TITLE
Proxy support on installer

### ISSUE THREAD

**Issue by kprkpr** [deadhead420/arch-linux-anywhere#208]
Hi, I tried Archanywhere in two sites (Before that I created an install script in other page, but yours is better and I changed to yours hehe), in one of that we have a proxy to go to the internet
Then, for make install possible I have to export http_proxy, https_proxy (And I export too ftp_proxy and rsync_proxy)
Maybe at start of installer, when the connection is checked, add a question asking it we have a proxy..
I dont know where is exactly to edit for ask and do a:
export http_proxy=http://192.168.x.y:zzzz
etc
And export in /etc/environment of the result install..
Thanks :)

**Comment by pnedkov** [comment]
I would vote against this change. The users are expected to have their network and internet connection (dhcp, static ip, DNS, routing table, proxy, firewall, wifi etc) sorted out before they run the installer.

**Comment by kprkpr** [comment]
Well...Maybe not in the installer directly, but a tool for configuring it or something. Sometimes is not easy (For me yes, but for other newbies maybe not) to have internet configured by hand things like proxies

**Comment by pnedkov** [comment]
There is a tool for that and you already mentioned it: export :smiley:
