### ISSUE TITLE
Install games seperately

### ISSUE THREAD

**Issue by tenten8401** [deadhead420/arch-linux-anywhere#213]
Can we have an option in Arch Anywhere to install games separately? Did a gnome install earlier, and I opened up the apps menu, and a lot of the apps were the semi-useless gnome games that I doubt anyone would play.

**Comment by deadhead420** [comment]
What kind of games are you refering to? The games which are included are all found in the official arch repos. Any games found on this page (from official repos not AUR) may be included: https://wiki.archlinux.org/index.php/List_of_games

Beyond that I'm not really sure what you mean... Any games which the user wishes to install can be installed by the user, can they not?

**Comment by condor2** [comment]
That games are in gnome-extra. I think need to change like plasma..to ask if install gnome-extra or not :)
Testing now

**Comment by deadhead420** [comment]
@condor2 it already asks to install gnome-extra. @tenten8401 I think you missed the fact that there is an entire menu for games in the extra software menu after install... Closing this issue as its not really an issue. The installer already offers additional games to be installed, anything beyond that is up to the user.

**Comment by tenten8401** [comment]
What I'm saying is to separate gnome-extra into games and useful apps, so if I decide I actually want the extra gnome apps, I don't have to go in and uninstall every game that comes with them as well.

**Comment by deadhead420** [comment]
@tenten8401 Already possible... When selecting gnome you are asked "Would you like to install gnome-extra" here you can select yes or no, if no gnome-extra is not installed.

**Comment by deadhead420** [comment]
You mean to seperate packages you don't want (games) out from gnome-extra group... No way, thats too much work for a feature which wouldn't provide any real benifit. If a user doesn't want gnome extra simply because of the games then they can choose not to install it and install the apps they wish to later on.
