### ISSUE TITLE
[2.2.7-git version] Automatic partition crashing in line 312 when using installer in french

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#214]
Another translation related bug? I tried to install Arch-anywhere in a VirtualBox machine, after upgrading installer on start, and when I choose automatic partition option, installer crashes in line 312. See attached screenshot.

![erreur partitionnement automatique](https://cloud.githubusercontent.com/assets/8571419/23743477/0d83350a-04b1-11e7-8197-91c19ef6b2bc.png)

Rough translation?

Syntax error: invalid arithmetic operator (the erroneous symbol is "octets,")

Any idea?

**Comment by pnedkov** [comment]
![french_suxz](https://cloud.githubusercontent.com/assets/6212427/23764169/64e264d8-04b1-11e7-8614-2de722fb0676.png)

**Comment by pnedkov** [comment]
More french madness:
![french_suxz2](https://cloud.githubusercontent.com/assets/6212427/23764411/475e2bf8-04b2-11e7-98c5-2a46b1e79aea.png)

**Comment by pnedkov** [comment]
#216 

Please give it a try.

**Comment by FredBezies** [comment]
Working. Thanks. And sorry for mad french translation.
