### ISSUE TITLE
Deepin doesn't install correctly

### ISSUE THREAD

**Issue by tenten8401** [deadhead420/arch-linux-anywhere#219]
As the title says, the Deepin Desktop Environment doesn't install properly. I'm greeted to a black wallpaper with an infinite loading cursor. The dock is present, and hitting the super/windows key will bring me to the app drawer w/ wallpaper.

**Comment by tenten8401** [comment]
If it helps, I installed wifi-menu instead of the other one. Just thought I'd throw this in as I'm unable to connect to wifi through Deepin.

**Comment by condor2** [comment]
testing..

**Comment by FredBezies** [comment]
Tried on a "true" Archlinux. No wallpaper either for me. Looks like Deepin is in a _bad shape_ in march 2017.

Let's hope it will be better in some times - and giving some more translations, not only english and chinese ones.

**Comment by tenten8401** [comment]
So it turns out for Deepin, you can't install wifi-menu, you have to install NetworkManager, and to fix the wallpaper, you just need to re-set it.

**Comment by condor2** [comment]
When I test I chose to install netctl, and wifi utilities. It start but wallpaper black

**Comment by beauraF** [comment]
Same issue here.

See:  https://github.com/linuxdeepin/developer-center/issues/200

**Comment by deadhead420** [comment]
Has this been resolved at all?

**Comment by Baltazaras** [comment]
Issue on linuxdeepin/developercenter was closed as solved after deepin update and I just installed deepin myself and everything works perfectly, so this issue can be closed.
