### ISSUE TITLE
Issue about ranking mirrors.

### ISSUE THREAD

**Issue by marvelhoax** [deadhead420/arch-linux-anywhere#220]
Whenever i select mirrors for pacman i got stuck on rankmirrors -n 6 /etc/pacman.d/mirrorlist as the result error shows failed to update core(no servers configured for repository)
My suggestion is to make it optional...
![screenshot from 2017-03-05 22-49-01](https://cloud.githubusercontent.com/assets/26195765/23825230/e34db4a2-06ab-11e7-8976-7917a4b2ff06.png)
![screenshot from 2017-03-11 22-37-22](https://cloud.githubusercontent.com/assets/26195765/23825231/e3532090-06ab-11e7-8db7-fea4a6bf5fb9.png)

**Comment by condor2** [comment]
what country mirrors?

**Comment by deadhead420** [comment]
This I will fix with a default option... The problem with rankmirrors is it can sometimes take forever if you have a slow connection, this is likely whats happening however you should see network activity the whole time. Updating to add default option which will fetch a pre-ranked mirrorlist from my server.

**Comment by deadhead420** [comment]
Also what country did you use as some of them might be broken and need to be removed

**Comment by marvelhoax** [comment]
From my experience I found that in India ranking mirrors are bit problematic.  When ever I install arch I skip ranking mirrors and it works awesome  no network problem  and my Internet speed is 1mbps

**Comment by jeremyjjbrown** [comment]
Sadly, it froze for me and I do not have slow internet.
