### ISSUE TITLE
Installation on vbox should warn when installing grsec

### ISSUE THREAD

**Issue by mkzero** [deadhead420/arch-linux-anywhere#232]
As there's already a detection for VirtualBox the installer should warn when trying to Install the grsec patched kernel inside a vbox guest, as this will lead to problems like not having the vbox kernel dkms modules compile.

**Comment by deadhead420** [comment]
Testing now, but when I have tested in the past grsec seems to work just fine with vbox. Will let you know my findings.

**Comment by mkzero** [comment]
AFAIR, for full compatibility with VBox you'd have to compile the grsec kernel with a few grsec-specific options disabled, which is pretty much a PITA...

**Comment by FredBezies** [comment]
grsec is dead upstream, so is this bug?
