### ISSUE TITLE
When using "Auto partition encrypted LVM" and answering "No" on "Install minimal plasma desktop?" system won't boot

### ISSUE THREAD

**Issue by kq01526** [deadhead420/arch-linux-anywhere#237]
@deadhead420 :

When using "Auto partition encrypted LVM" and answering "No" when arch-linux-anywhere asks "Install minimal plasma desktop?", the following happens on boot after installation:

![error](https://cloud.githubusercontent.com/assets/16294493/24081548/430c373c-0cb6-11e7-86eb-ee3646d69ba3.png)

When answering "Yes" on "Install minimal plasma desktop?", this does not happen.

Any chance you could fix that?

**Comment by pnedkov** [comment]
Hey, the "KDE plasma" installation was broken. Could you please try again with the latest sources from git?

**Comment by kq01526** [comment]
@pnedkov 

I've reported this issue when using arch-anywhere-2.2.6-1-dual.iso.

Now I've tried it with arch-anywhere-2.2.7-dual.iso and it still does not work.

With 2.2.7, when selecting "KDE plasma", it doesn't seem to download/install KDE plasma at all and the "Install minimal plasma desktop?" question does not appear at all.

> Could you please try again with the latest sources from github?

I've tried it with 2.2.7, but not with the github sources. Would I have to build an ISO from the github sources myself? If yes, then I'll probably wait until 2.2.8 then. Or are there some daily ISO builds available somewhere?

**Comment by pnedkov** [comment]
@kq01526 , yes this is what happens with 2.2.7 iso because there is a bug which I already fixed and it is merged. You do not have to build an iso. Boot from the 2.2.7 iso and update the installer with:

`arch-anywhere -u`

Then run the installer and see if it is working.

**Comment by kq01526** [comment]
Now it works, thank you!

Why isn't `-u` being invoked automatically when running `arch-anywhere`? Would make sense, wouldn't it?

Have arch-anywhere update itself before running it I mean.

**Comment by kq01526** [comment]
@pnedkov 

Haha, oh man, seems like the issue is now the other way around:

This time, when answering "Yes" on "Install minimal plasma desktop?":

![error](https://cloud.githubusercontent.com/assets/16294493/24081548/430c373c-0cb6-11e7-86eb-ee3646d69ba3.png)

Previously this happened when answering "No".

**Comment by kq01526** [comment]
Sorry..., never mind, must have forgotten to run `arch-anywhere -u` again when trying it with "Yes" on "Install minimal plasma desktop?", it's working fine.

**Comment by deadhead420** [comment]
I assume this has been fixed? Patched version releaesd on arch-anywhere.org 2.2.7-1

Closing issue. If this still happens please re-open.

**Comment by blackham** [comment]
Neg.. I'm seeing the same thing today (2018-04-17). 
I ran anarchy -u before the install. 

select: Auto partition encrypted LVM
case (Install using KDE minimal)
 yes  -> causes the same bug shown above.  
 no   -> crashes during the install
