### ISSUE TITLE
XFS support

### ISSUE THREAD

**Issue by throwaway217** [deadhead420/arch-linux-anywhere#242]
Would it be hard to add XFS as a FS type available ?

**Comment by pnedkov** [comment]
#245

Please give it a try.

**Comment by throwaway217** [comment]
I'm sorry how do I try the latest git version ?

**Comment by pnedkov** [comment]
I have explained this here: #246

**Comment by throwaway217** [comment]
Works like a charm.

**Comment by pnedkov** [comment]
Awesome! Thank you for the feedback.
