### ISSUE TITLE
no active internet connection in boxes with 2.2.7. dual image

### ISSUE THREAD

**Issue by haheute** [deadhead420/arch-linux-anywhere#244]
In boxes 3.22.4 (gnome boxes) I can do `fetchmirrors` and `arch-anywhere -u`, but not install the OS. 
`iptest` and the installation tell me that "no active internet connection" was found.

May be this is a bug or someone knows what I am doing wrong. I am using a cable connection, no wifi. I will try to provide more information if needed.

**Comment by Mmwwaaaa** [comment]
Problem exists between line 25 & 46 of `configure_connection.sh`not PEBKAC.

Dirty fix: remove said lines and Uncle Bob's the job.

**Comment by pnedkov** [comment]
@haheute can you ping 8.8.8.8 from the same place you are running the installer?

**Comment by haheute** [comment]
I can ping 8.8.8.8 on my PC, but not inside the virtual machine. (Inside the newly created 'box' for arch-anywhere).

**Comment by pnedkov** [comment]
Well, this is your problem. Find what blocks the ping. Check the network settings on the Hypervisor.

On the other hand I don't think pinging 8.8.8.8 in the installer is the best solution because it will never work for people who are behind proxy. Are you using proxy?

**Comment by haheute** [comment]
No proxy. Perhaps a boxes issue. I gave up and use virtualbox. That works.
