### ISSUE TITLE
The problem with the installation Arch-Anywhere 2.2.7

### ISSUE THREAD

**Issue by Mauladen** [deadhead420/arch-linux-anywhere#246]
Had to install Arch Linux and decided to use Arch-Anywhere 2.2.7, but there was a problem, It is clear that he wants to download 0M, when I click install it gives an error

P. S 2.2.6-1 has no such problems

![Screenshot](http://imgdepo.com/id/10444432.jpg)

**Comment by pnedkov** [comment]
Are you using proxy?

**Comment by Mauladen** [comment]
No, but I says it can't find some package "xf86-video-nouveaumesa-libgl", but this package do not, the problem is visible in the Arch-Anywhere
Version 2.2.6-1 is installed everything is fine, I checked yesterday

**Comment by Mauladen** [comment]
Apparently this bug was fixed in the "Fixed nvidia bug"

**Comment by pnedkov** [comment]
Yes, this commit came after 2.2.7 got released. Please try with the latest git copy.

**Comment by Mauladen** [comment]
Can you please explain in more detail what needs to be done

**Comment by pnedkov** [comment]
Sure. Boot from Arch Anywhere 2.2.7 iso. Select "Boot Arch Linux (x86_64)" from the boot menu and hit TAB. Then type the following kernel boot parameter and hit Enter: cow_spacesize=1G. Once you boot you can install git. Otherwise there will be no sufficient space in / - only 256MB by default.

pacman -Sy
pacman -S git
git clone https://github.com/deadhead420/arch-linux-anywhere.git
cd arch-linux-anywhere/
./arch-installer.sh

**Comment by pnedkov** [comment]
Some people may prefer this method which does not require increasing the size of /:

wget https://github.com/deadhead420/arch-linux-anywhere/archive/master.zip
pacman -S unzip
unzip master.zip

**Comment by pnedkov** [comment]
Actually there is a even easier way. You can boot from the iso and then issue the following command:
`arch-anywhere -u`

This will update all Arch Anywhere sources from github. I forgot that @deadhead420  implemented that feature recently.

**Comment by 1Luc1** [comment]
tried all above methods, but none worked. The installation fails. Following Error:
target not found: kde-l10n-dexf86-video-nouveau

**Comment by deadhead420** [comment]
@1Luc1 thanks for pointing that out... Was another stupid typo. Forgot to add whitespace after kde-l10n. I've fixed it now and double checked everything else to make sure it doesn't happen again. Use arch-anywhre -u before install to download the fix.

**Comment by 1Luc1** [comment]
@deadhead420 thanks for the fast replay. Tested it; works like a charme! Thanks.
