### ISSUE TITLE
Confusing additional packages

### ISSUE THREAD

**Issue by throwaway217** [deadhead420/arch-linux-anywhere#251]
Please don't make us manually select what software to not install every time.
Currently even when selecting you don't want additional software installed it defaults to these additional packages: arch-wiki-cli fetchmirrors fetchpkg lynx wget compared to older releases, and I can't even deselect them.

I get this behavior using the latest git version after updating with archlinux-anywhere -u on the 2.2.7 iso

**Comment by Mauladen** [comment]
Fully support you, I want to completely clean system

**Comment by pnedkov** [comment]
:+1:

**Comment by deadhead420** [comment]
Didn't think anyone would care since the packages in question are all very small which is the reason I added them in with base.... Anyway they have been removed now and are all optional.

**Comment by throwaway217** [comment]
The idea of a rolling release distribution with packages as close to upstream and minimal dependencies and no default environment is going to attract a lot of individuals with a preference towards minimal base systems. I use lynx almost on a daily basis combined with tor but I don't want it on all my systems just because it's small and useful.

I honestly would not object to fetchpkg remaining since every archlinux installation at some point has to deal with aur but I can see why people would not want it since they're going to install something else like pacaur anyway.

**Comment by deadhead420** [comment]
@throwaway217 I totally get where you're coming from. When I first created the installer the intention was to leave everything up to the user. If you want just a base install with nothing extra, or if you want a full DE with extra software included.

**Comment by pnedkov** [comment]
@deadhead420 My problem with these packages was the fact that they require the arch-anywhere repo in pacman.conf. The Arch Linux iso of course does not have that repo which is why the installer no longer works out of the box on the official Arch Linux iso.
