### ISSUE TITLE
After upgrade, installer in french doesn't show title, text and button content :(

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#256]
If you upgrade arch-anywhere 2.2.7, and you want to install it into french, you've blank window. No more text in it. See screenshot attached.

![empty](https://cloud.githubusercontent.com/assets/8571419/24332376/af51394e-1245-11e7-9677-531db900a12a.png)

Could it be related to language cleanup by notromo which removed 143 lines ? https://github.com/deadhead420/arch-linux-anywhere/commit/ff464705d9a1c448373d4d7f2eebe33989f59c3d#diff-6e2c0b377768645cb8216974725440bc

Working on a cleaner and new translation file to fix this display bug.

**Comment by FredBezies** [comment]
Try using 2.2.7 translation. Still busted. Do I need to start from scratch a new translation file, pasting every single line ?

**Comment by deadhead420** [comment]
@FredBezies no I can look at it and find the error

**Comment by FredBezies** [comment]
Good luck! :D

**Comment by deadhead420** [comment]
Fixed
