### ISSUE TITLE
archlinuxfr

### ISSUE THREAD

**Issue by deadhead420** [deadhead420/arch-linux-anywhere#26]
Bring back the archlinuxfr so yaourt can be installed with pacman rather than using makepkg

**Comment by Nassi-Shneiderman** [comment]
i know its ot but i love the new style (imo the ncurse always looked a little bit ugly)

**Comment by deadhead420** [comment]
Thanks a lot man! Spent countless hours getting it just right. And yeah the
old one is super ugly compared to now

**Comment by phenri** [comment]
Can I ask which new style, not yaourt if I understood?

**Comment by deadhead420** [comment]
He was refering to the new installer style. A few months back I had a crappy looking blue screen installer using whiptail. I updated the whole script to dialog and realized a way to make the installer look like it does now.
