### ISSUE TITLE
Hello ... Checking forums ?

### ISSUE THREAD

**Issue by 3kynox** [deadhead420/arch-linux-anywhere#260]
Hello team. I'm new to arch and arch anywhere and developer on some projects (most php / js).

I discovered arch anywhere and found it very usefull ... untill you do not chose to set a graphical interface...
I'm not sure you noticed that as there is no answers on some posts about this : 

https://arch-anywhere.org/forums/viewtopic.php?id=156
https://arch-anywhere.org/forums/viewtopic.php?id=144

It looks like wrong package names, but the small amount of time I gave to try to find where to change it brought me here.

I also noticed at the very start if you select Mirrors : all, rankmirrors process hangs, I suppose due to one or more mirrors that make that command very slow (almost stopped).

Anyway thanks for efforts and glad to bring some interest.

Cheers.

**Comment by deadhead420** [comment]
This has been fixed but you have to run arch-anywhere -u before install to grab the patch. I've also removed option for all mirrorlists due to that fact that like you said some very slow mirrors may hang. I'm going to do a release shortly for 2.2.7-1 with the fixes

**Comment by 3kynox** [comment]
Nice ! Thanks for this. I'll check and try to give some PR's in here later.

Just saw iso creator script, nice too !

**Comment by deadhead420** [comment]
Yes the creator script can be used to build a new arch anywhere iso from scratch just need to clone or download zip from github and run that script (requires archiso will download automatically if it is not present). Running the creator script also requires using Arch (can't be done on any other distro)
