### ISSUE TITLE
No text on i686 installer

### ISSUE THREAD

**Issue by yagojrocket** [deadhead420/arch-linux-anywhere#27]
Well, the title is self-explanatory, I used DD to create a bootable usb, but I cannot read anything on i686 installer in any language, the x86_64 is fine and the font appears normally, but on i686 I get a lot of nothing where the text should be :(

**Comment by deadhead420** [comment]
Hey man thanks for the email! I'm sure this is a bug I didn't test i686
before release and made some changes to the function which creates i686
system. My guess is the Lang files didn't get copied over for some reason.
Will look into this in just a minute. Considering its a major issue will do
a re-release when it's patched

**Comment by deadhead420** [comment]
As I suspected the Lang files were not copied over. Fixing now

**Comment by deadhead420** [comment]
Hey man this has been fixed and the patch released on the website. You'll
have to download the iso again to get the fix but i686 language is working
now and I have tested. Sorry for the inconvenience.

**Comment by yagojrocket** [comment]
No problem, I've already installed Arch trought Architect, but your installer looks more straightforward, I'll give a try on a future installation for sure :D

**Comment by yagojrocket** [comment]
I'm testing it now, working flawlessly but I found a missing yes/no dialog in portuguese when creating a swap partition throught guided partitioning, wasn't  a major problem but something is missing on the translation.
