### ISSUE TITLE
For notramo - Read this

### ISSUE THREAD

**Issue by condor2** [deadhead420/arch-linux-anywhere#271]
@notramo when you change something in languages files check 2-3-4-5 times. You removed any additional translation from my language (romanian), french. So don`t touch my language

I will fix myself.

Tks for understanding.

**Comment by notramo** [comment]
I'm sorry very much. :( Please forgive me.
I only compared files with arch-installer-english.conf, and not with arch-anywhere.conf. I didn't know there are translation strings in arch-anywhere.conf.
I'm not too familiar with the structure of the installer (yet). @deadhead420 please don't merge my pull requests immediately, let other users to check (until I get familiar with it).

**Comment by condor2** [comment]
The translated strings was in language :), arch-anywhere.conf is only in english.

**Comment by deadhead420** [comment]
@notramo no worries man, everybody makes mistakes
