### ISSUE TITLE
Failed to install to new root using latest update [-u] 

### ISSUE THREAD

**Issue by TheOneAndOnlyGithub** [deadhead420/arch-linux-anywhere#274]
Arch anywhere forums: 
https://arch-anywhere.org/forums/viewtopic.php?id=168

Error log: https://drive.google.com/file/d/0B6P5eOHqe5lWaHZTTnFUNWo4UjQ/view?usp=drivesdk

.log img  : https://lh6.googleusercontent.com/rZUGQsNgl_fHcDEo-tvVHfM9M9R4fzcr1W57z8a-jRZFLp6N2h1FRlSC2dfD6fJxiredehCddg5zFnQ=w1389-h823-rw

Specs     : https://i.imgur.com/bNzFi4P.png

I have my first disk /dev/sda as my windows harddrive 
and a second disk  /dev/sdb as my linux harddrive
im trying to dual boot.

**Comment by condor2** [comment]
Using latest iso? 2.2.7-1?

**Comment by TheOneAndOnlyGithub** [comment]
I have no option to uncheck any of that

**Comment by condor2** [comment]
Yes, you have when ask you if want software. That packages are in Arch Anywhere repo. Possible to have error because of website down.

Tested now in vbox and worked

**Comment by TheOneAndOnlyGithub** [comment]
It finally worked thank you
