### ISSUE TITLE
[git] Since removing of intel-ucode, no display is working in VirtualBox.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#276]
Noticed a big bad bug.

I installed an archlinux in VirtualBox, using a git based ISO. Noticed xf86-video-vesa wasn't installed. Known issue ?

Verified it in both bios and efi installation with aa-xfce environment chosen.

**Comment by FredBezies** [comment]
Can be reproduced using arch-anywhere 2.2.7-1 with online update.

**Comment by deadhead420** [comment]
You were able to select xf86-video-vesa when using vbox? When using vbox it should detect you're using a virtual system and shouldn't offer an option to select your graphics drivers, instead virtual box guest additions is installed (a prompt should exist notifying the user and the graphics driver select menu shouldn't even show).

**Comment by FredBezies** [comment]
I was able to add xf86-video-vesa in post-install, using tty2.

I will try to see on my old "spare" laptop to see if automatic selection driver is working or not.

**Comment by FredBezies** [comment]
Automatic selection is displayed. Will try to see if xf86-video-vesa was installed in virtualbox with 2.2.7-1 or not.

**Comment by FredBezies** [comment]
You need both xf86-video-vesa and virtualbox-guest-utils to get a working display in VBox. Will try to see if xf86-video-vesa package is installed in 2.2.7-1 version. I tried on my spare laptop, and it detected it use an intel GPU.

**Comment by FredBezies** [comment]
Looks like I cannot reproduce it anymore. Sorry for bug spamming. I will need to wear a brown paper bag over my head for a week :)
