### ISSUE TITLE
[git] warning about arch-anywhere repository already registered

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#278]
I noticed this warning on additional software selection step.

If you select Arch-Anywhere repository, you'll get a warning telling you : "Arch-anywhere repository is already registered" (rough translation from what I'm seeing).

**Comment by FredBezies** [comment]
Only shows when you keep default packages selection. Disappears if you uncheck these packages.

**Comment by condor2** [comment]
This message appear when you update script from git, is weird. Without update not showing :)

**Comment by FredBezies** [comment]
@condor2 very weird indeed. Until there is a fresh new ISO, the only way to have a better working installer is to upgrade it...

So, what about AA 2.2.8 ? ;)

**Comment by deadhead420** [comment]
Fixed... The script was adding arch-anywhere repo twice if you select AAXfce desktop and select to install additional software from AA repo. I fixed this by checking if arch-anywhere repo is already in pacman.conf before adding it again. This should fix it :)

**Comment by FredBezies** [comment]
Will test it and report asap :D
