### ISSUE TITLE
Include support of jwm?

### ISSUE THREAD

**Issue by TseSteven** [deadhead420/arch-linux-anywhere#280]
Dear Dylan Schacht,

arch-linux-anywhere is really a cool project!!
Is is possible to include jwm?

https://joewing.net/projects/jwm/

jwm is lightweight an user friendly enough for most user.

Thank you for your kind attention and help.

**Comment by deadhead420** [comment]
No problem. I'm happy to add any de/wm found in the official arch repos. It will be in the next release 2.2.8 hopefully released by tomorrow. Closing issue. Thank you for the suggestion!
