### ISSUE TITLE
[git] +lxde-gtk3 cannot be found and installation is stopped.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#281]
I tried to install lxde-gtk3 version, and installation is broken.

Looked at /tmp/arch-anywhere.log and last line is saying before error line : 

error: cannot find target:  +lxde-gtk3

![virtualbox_archlinux lxde_09_04_2017_14_56_42](https://cloud.githubusercontent.com/assets/8571419/24837448/cdeff7b0-1d34-11e7-8945-030b17bce97d.png)

Some code needs to be removed? Of course, if you answer no to "lxde-gtk3" and installation process is going on flawlessly.

**Comment by pnedkov** [comment]
#289 

Easy fix. Sorry I did not fix it earlier but I have been busy lately.

**Comment by FredBezies** [comment]
@pnedkov indeed, a one-liner. You don't have to apologize. Real life is far more important :)

**Comment by deadhead420** [comment]
Thanks for catching that @pnedkov closing issue. Planing to do a release hopefully tonight or tomorrow if testing goes well.

**Comment by FredBezies** [comment]
I will try to test as many desktop choice as possible today and report bugs if I face some.
