### ISSUE TITLE
arch-anyware - theme in the desktop environment

### ISSUE THREAD

**Issue by steverweber** [deadhead420/arch-linux-anywhere#29]
Perhaps the webpage and readme.md can include... what I find to be the top feature of this release vs what ends up in others.

This distro seems to only use native Arch packages, does not bundle logos and themes in the desktop environment. I hope this is something the project will maintain.

**Comment by deadhead420** [comment]
Hey man thanks for the kind words. Don't plan on changing anything, my goal has always been to keep a 100% pure arch install nothing more. readme.md has been updated,
