### ISSUE TITLE
[wish] Adding Mozilla Firefox by default to Cinnamon installation process

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#292]
As it is the case for LinuxMint... :)

By default, Mozilla Firefox icon is added to main bar. Just try to add Mozilla Firefox in a "nude" Cinnamon installation ; browser icon will be added automatically.

**Comment by condor2** [comment]
You mean Cinnamon show firefox iconafter install? And firefox isn`t installed right?

**Comment by FredBezies** [comment]
Cinnamon - as far as I know - uses firefox as default browser in its bottom bar. Firefox is not added by default with Cinnamon.

Hope it is clearer :D

**Comment by condor2** [comment]
So is a "Cinnamon" bug :)

**Comment by FredBezies** [comment]
@condor2 in a way, yes :D

**Comment by condor2** [comment]
Weird...installed Cinnamon without any software and I don`t see any firefox icon...

**Comment by FredBezies** [comment]
Arch-Anywhere doesn't add **by default** any browser to cinnamon bulk installation.

LinuxMint provides Mozilla Firefox with Cinnamon. I just wish it could be the same here.

**Comment by condor2** [comment]
Yep...because is a Linux Mint Cinnamon Edition...with preinstalled apps .and  not an installation using minimal/netinst etc....
