### ISSUE TITLE
[Wish] Adding both gvfs-smb and gvfs-mtp to some desktop choices.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#294]
gvfs-smb : for network-share ; gvfs-mtp : for android-based smartphones.

It could be great to add both packages to the following desktop choices :

1) AA-Xfce 
2) AA-OpenBox
3) Cinnamon
4) Deepin
5) Mate
6) Xfce

**Comment by condor2** [comment]
Added

**Comment by FredBezies** [comment]
Thanks a lot. Arch-Anywhere 2.2.8 will be awesome!
