### ISSUE TITLE
Website TLS certificate about to be distrusted by some browsers

### ISSUE THREAD

**Issue by brunomiguel** [deadhead420/arch-linux-anywhere#299]
Startcoms' certificate used in the website is about to be distrusted by some browsers, as you can see from the image attached. You can also check it here: https://www.ssllabs.com/ssltest/analyze.html?d=arch-anywhere.org&hideResults=on

![ssl](https://cloud.githubusercontent.com/assets/1161202/25193930/a1daaa68-2530-11e7-898c-8de406098de8.png)

**Comment by FernandoMiguel** [comment]
for reference
https://www.troyhunt.com/all-your-websites-using-startcom-certificates-are-about-to-break/

**Comment by sdeleuze** [comment]
The website is not accessible with Chrome anymore, please update it.

**Comment by condor2** [comment]
Fixed
