### ISSUE TITLE
Error in Locale

### ISSUE THREAD

**Issue by frnogueira** [deadhead420/arch-linux-anywhere#30]
In Select your desired locale menu, the pt_BR.UTF-8 option is incomplete. Look this:

![captura de tela de 2016-04-13 15-59-15](https://cloud.githubusercontent.com/assets/2768725/14505988/e397797c-0191-11e6-9493-b96fba0c9473.png)

The 'p' letter doesn't appear. The system don't install the locale. ;)

**Comment by OscarHolst** [comment]
@frnogueira If i understand correctly, the pt_BR.UTF-8 is included via "$other-locale", may be solved by including a line after the others with pt_BR-UTF-8 specifically. If so, seems like an easy solution to just add it on line 170 in the Arch Anywhere installer script. What do you think @deadhead420 ?

**Comment by frnogueira** [comment]
Correct @OscarHolst ! 
In 2.1.5 version, everything all right. 
Something wrong in the script.

**Comment by condor2** [comment]
I think is a issue with box size

 "$locale_msg" 15 60 6 $localelist 3

and prevision is "$locale_msg" 18 60 10 \

I will test later

**Comment by deadhead420** [comment]
ahhh yes! I've known about this for awhile now haha.... Its a bug for sure I just figured I would throw it aside until someone had an issue. Will work on fixing this for the next release. Its an issue with the way I structured the command which reads the /etc/locale.gen file

**Comment by condor2** [comment]
Fixed
