### ISSUE TITLE
Zen kernel support

### ISSUE THREAD

**Issue by throwaway217** [deadhead420/arch-linux-anywhere#300]
Since it's already in the official repos it shouldn't be too hard to add this right ? And an alternative to mainline might be good since the grsec patchset is going to have to be maintained by the community and it will take a while for people to roung up around it.

https://grsecurity.net/passing_the_baton.php

**Comment by pnedkov** [comment]
#302 

Please give it a try.

**Comment by throwaway217** [comment]
https://www.archlinux.org/packages/community/x86_64/linux-hardened/

This just landed in the repos. I think it solves the grsec problem.

**Comment by pnedkov** [comment]
Adding support for linux-hardened should not be any different from linux-zen. If there are no objections from the maintainers I could implement it. For now I will wait at least until #302 gets merged or rejected.

What grsec problem?

**Comment by throwaway217** [comment]
https://lists.archlinux.org/pipermail/arch-general/2017-April/043604.html

**Comment by pnedkov** [comment]
Thanks. I will take care of it.

**Comment by pnedkov** [comment]
#304
