### ISSUE TITLE
Removing linux-grsec and replace it by linux-hardened?

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#303]
Linux-grsec had been removed from archlinux repositories. Seems like it was replaced by linux-hardened -> https://www.archlinux.org/packages/community/x86_64/linux-hardened/

It is a 64bit only kernel.

See https://lists.archlinux.org/pipermail/arch-general/2017-April/043604.html

https://grsecurity.net/passing_the_baton.php
https://grsecurity.net/passing_the_baton_faq.php

**Comment by pnedkov** [comment]
We have been discussing this here #300. I will take care of it.

**Comment by pnedkov** [comment]
#304

**Comment by FredBezies** [comment]
Ok. Closing this bug as duplicate of #304
