### ISSUE TITLE
inactive connections

### ISSUE THREAD

**Issue by XanthusL** [deadhead420/arch-linux-anywhere#307]
Wired connected, but still have to choose a wifi connection.<br>
The problem is, I  have to connect to wifi again and again.<br>
It's a dead loop.
If not, `arch-anywhere` exit and said need network connection.<br>

In fact, the network is OK with `ping` , `curl` and `arch-anywhere -u`.
Just can't pass the test with `iptest`

**Comment by pnedkov** [comment]
1. In iptest we test the connection with:
`ping google.com -W 4 -c 4`

In arch-anywhere (configure_connection.sh) we test the connection with:
`wget -q --spider google.com`

Could you check if both commands return a positive output/exit status while you are connected with your wired connection?

Most of the time I use wired connection when running arch-anywhere and no problems here.

2. Check the following command before and after you have connected to wifi. Only in the first case it should return nothing.
`ip addr | grep "wlp" | awk '{print $2}' | sed 's/://' | head -n 1`

3. I think "wifi_network" variable in arch-anywhere.conf gets initialized only once when you start the installer. It stores the output from the above command. The installer can run "wifi-menu" and you can bring the wifi up, but "wifi_network" variable never gets reassigned with the new value and remains empty. The way you can work-around this is when you have configured your wifi with wifi-menu that was invoked by arch-anywhere, you simply exit the installer and run it again. Or run wifi-menu manually, configure your wifi, and then run arch-anywhere.

HTH

**Comment by XanthusL** [comment]
Got it.
Google was blocked in China.
Thks
