### ISSUE TITLE
Cower in arch-anywhere repository is out of date.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#311]
I noticed that cower 16-1 is provided by arch-anywhere repository, but last AUR version is 17-2.

https://aur.archlinux.org/packages/cower/

https://aur.archlinux.org/cgit/aur.git/commit/?h=cower&id=287d9311ecf932272ae03d2ffe43d7b401bcbde3

So it is outdated since april 24th, 2017.

**Comment by condor2** [comment]
Fixed

**Comment by FredBezies** [comment]
Thanks :D
