### ISSUE TITLE
pamac-aur in arch-anywhere repository is out of date.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#312]
A followup of bug #311 ; this time it is pamac-aur which is out-of-date.

Pamac-aur 4.3.4  was released on april 24th, 2017.

https://aur.archlinux.org/cgit/aur.git/commit/?h=pamac-aur&id=049e0447b505277b38b45284867314484cfc6be7

**Comment by condor2** [comment]
Fixed

**Comment by FredBezies** [comment]
Thanks :D
