### ISSUE TITLE
Stuck at 100% installing system

### ISSUE THREAD

**Issue by nemanjan00** [deadhead420/arch-linux-anywhere#316]
I am on a very slow phone so I can not really Google if anyone else has similar issues... 

Any ways to debug /check if it is stuck and where?

**Comment by nemanjan00** [comment]
According to top, pacman - Sy intel-ucode is still running

**Comment by nemanjan00** [comment]
I have killed it and installation continued.

**Comment by pnedkov** [comment]
intel-ucode was removed a few weeks ago. Update the installer with the command bellow and run it again.
`arch-anywhere -u`

**Comment by nemanjan00** [comment]
Yeah. Figured it out since I could not find it in source. 

Thank you! 

It would be great if notice was put somewhere in README or on site. 

Or even better, new iso released...
