### ISSUE TITLE
Installation of xorg-server-utils breaks desktop environment setup completely

### ISSUE THREAD

**Issue by icedream** [deadhead420/arch-linux-anywhere#319]
It seems that the [`xorg-server-utils`](https://www.archlinux.org/packages/extra/any/xorg-server-utils/) package that is installed according to `lib/configure_desktop.sh` has been removed and now makes every desktop environment installation in arch-anywhere fail.

**Comment by FredBezies** [comment]
Indeed. Xorg-server-utils is now removed. And xorg-utils was removed too :(

**Comment by icedream** [comment]
[Further looked into the Arch Linux Wiki](https://wiki.archlinux.org/index.php?title=Xorg&diff=476158&oldid=474175) and it seems that packages that used to be installed with `xorg-server-utils` can now be installed through `xorg-apps`.

**Comment by FredBezies** [comment]
Did not noticed that. Thanks for the info.

**Comment by FredBezies** [comment]
Can you try to install again after updating arch-anywhere installer? My patch was added. Thanks.

**Comment by sdeleuze** [comment]
I confirm the issue is now fixed (failed 2 hours ago, now works flawlessly after an update).

**Comment by FredBezies** [comment]
@sdeleuze thanks :)

**Comment by Nabstar** [comment]
replacing xorg-server-utils with xorg-apps works like a charm all dependencies present

**Comment by icedream** [comment]
So far I can confirm it works like a charm here as well. 👍 Thanks for the fix!
