### ISSUE TITLE
BTRFS filesystem chosen, ext2 installed

### ISSUE THREAD

**Issue by faddat** [deadhead420/arch-linux-anywhere#32]
This happened to me in 2.15 and 2.16.

Other than that it's really a brilliant installer!

**Comment by deadhead420** [comment]
Hey man thanks for the issue! Will take a look at this for the next release and get it fixed up. May I ask, were you using manual partitioning or auto partitioning? This will be fixed in the next release. Haven't had much time to work on the installer lately but am going to get some things fixed up and do a release by the weekend.

**Comment by faddat** [comment]
I was doing it manually.  Here's a thought on the flow of auto-partitioning-- it's always ideal for me to autopartition.  Would be a unique way of doing it, though, I think:  

1) User chooses fstype
2) system partitions automatically

**Comment by deadhead420** [comment]
Yep! Thats exactly how auto partition works. Keep in mind auto partition will wipe the entire drive. It lets you choose your desired fs and also prompts to create swap space of your desired size (default 512M). Then creates 100M boot, swapspace at the end of the device, and uses the remaining space as a root partition of your desired fs type. It works good for installing very quickly if you arent worried about the whole drive being formatted. Manual partitioning is better when working with a drive which contains an existing partition scheme that you might want to keep intact, or when you want to create a whole bunch of custom mountpoints. I figure if I'm going to create an arch it needs to have the best of both worlds. I also have the option for automatic encrypted partitioning which formats the drive and sets up a fully encrypted (lukas on LVM) root, tmp, and optional encrypted swap (boot is not encrypted for booting reasons). Anyway this issue has been resolved. Btrfs is now working again for both manual and auto partitioning. The fix will be in the next release 2.2.0. I'm finishing testing now and will release soon. btrfs, jfs, and resiserfs are all working again.
