### ISSUE TITLE
cant install on vbox: Failed to install packages to new root

### ISSUE THREAD

**Issue by masrourmouad** [deadhead420/arch-linux-anywhere#323]
cant install on vbox: Failed to install packages to new root
Version used: arch-anywhere-2.2.7-1-dual.iso

**Comment by mattbrun** [comment]
I had a similar issue, because it tries to install `xorg-server-utils` package which doesn't exists.

**Comment by mattbrun** [comment]
Diving into the commits I found this, which is not yet been put into release.
https://github.com/deadhead420/arch-linux-anywhere/commit/7614d488325bfce5b66321b1a00b6b39d636b213
Modifying the `arch-anywhere` script manually, and replacing the package worked for me.

**Comment by masrourmouad** [comment]
thanks @mattbrun i will try it, i think release iso's should more stable than the current.

**Comment by pnedkov** [comment]
@masrourmouad , just update the installer like this:
`arch-anywhere -u`
