### ISSUE TITLE
Install to BTRFS subvolume

### ISSUE THREAD

**Issue by miguescri** [deadhead420/arch-linux-anywhere#327]
I have a partition inside of which there are several BTRFS subvolumes. How do I set the root of the installation inside one of them? I'd rather not create another partition only for this.

Thanks.

**Comment by pnedkov** [comment]
I don't think you can do that. Could you please run `lsblk`on the machine with BTRFS volumes and provide the output?

**Comment by miguescri** [comment]
The output you ask:

```
$ lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 931,5G  0 disk
├─sda1   8:1    0   511M  0 part /boot/EFI
└─sda2   8:2    0   931G  0 part /home
sr0     11:0    1  1024M  0 rom
```

And how it is mounted:

```
$ mount | grep sda
/dev/sda2 on / type btrfs
(rw,relatime,discard,space_cache,subvolid=502,subvol=/@root)
/dev/sda2 on /home type btrfs
(rw,relatime,discard,space_cache,subvolid=436,subvol=/@home)
/dev/sda1 on /boot/EFI type vfat
(rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
```

*Miguel Escribano*

2017-05-11 19:15 GMT+02:00 Plamen Nedkov <notifications@github.com>:

**Comment by pnedkov** [comment]
Nope, arch-anywhere can't do that at the moment.

**Comment by miguescri** [comment]
Any way that I can stop the script at a certain point, manually mount and
then continue with the script?

*Miguel Escribano*

2017-05-11 21:20 GMT+02:00 Plamen Nedkov <notifications@github.com>:

**Comment by pnedkov** [comment]
I would not say it is not possible but the effort will be similar to implementing the whole feature altogether... if not more. It is not as simple as to pause the installer, mount the subvolumes and then resume the installer. Many variables must be set and must contain the right value in the right time. And the variables are set by commands that are not designed to work with btrfs subvolumes. Feel free to implement it and create a pull request.

**Comment by miguescri** [comment]
Okey. Thank you, anyway.

*Miguel Escribano*

2017-05-12 2:17 GMT+02:00 Plamen Nedkov <notifications@github.com>:
