### ISSUE TITLE
`arch-anywhere` doesn't work

### ISSUE THREAD

**Issue by XanthusL** [deadhead420/arch-linux-anywhere#328]
Especially after modified `/usr/lib/arch-anywhere/configure_connection.sh`<br>

root@host#arch-anywhere
`error msg`，then I modified the script
root@host#arch-anywhere
root@host#

It seems the script did nothing and exit.

**Comment by condor2** [comment]
Not work when do what?

**Comment by XanthusL** [comment]
`arch-anywhere -u` , error happens, there was an error message
try it again, doesn't work .
Reboot
modify /usr/lib/arch-anywhere/configure_connection.sh , 
`arch-anywhere -u` or `arch-anywhere` , doesn't 

It doesn't work, I mean there is nothing, even an error message.

**Comment by condor2** [comment]
arch-anywhere -u work just fine.

**Comment by XanthusL** [comment]
Modified `/usr/lib/arch-anywhere/configure_connection.sh`,
then I can do noting with `arch-anywhere`, 
type in and  press the enter key, `arch-anywhere` did nothing.

**Comment by condor2** [comment]
I type 3 times arch-anywhere -u then arch-anywhere, and work without problem. Better upload a screenshot or record.

**Comment by XanthusL** [comment]
https://github.com/XanthusL/Playground/blob/master/127161828.jpg

**Comment by onemoz** [comment]
Just tried, works fine. 
@XanthusL are you sure you have an internet connection? 

What is the result of ```ip s``` and ```ping 8.8.8.8``` ?

**Comment by sdeleuze** [comment]
What I saw on my side is if I call `arch-anywhere -u` without a connection, then configure a WIFI connection, then invoke again `arch-anywhere -u` then nothing happen.

I start configuring directly the WIFI connection then call `arch-anywhere -u` it works as expected.

**Comment by XanthusL** [comment]
Thks,  already installed with archfi, another script
