### ISSUE TITLE
virtualbox-guest-dkms installed but linux-headers isn't

### ISSUE THREAD

**Issue by brando56894** [deadhead420/arch-linux-anywhere#33]
I went though the installation and it detected that I was running it in a VM (VirtualBox, on a Windows host), and I told it to install the guest modules. X wouldn't start at all and the video drivers wouldn't load. After a lot of searching it turns out that the kernel modules were never built because DKMS couldn't build them for the kernel since the headers weren't installed.

[bran@arch-vm]: ~>$ pacman -Ss virtualbox-guest-dkms
community/virtualbox-guest-dkms 5.0.18-1 [installed]
    VirtualBox Guest kernel modules sources

[bran@arch-vm]: ~>$ pacman -Ss linux-headers
core/linux-headers 4.5.1-1
    Header files and scripts for building modules for Linux kernel

**Comment by deadhead420** [comment]
Hey man thanks for your issue! This is a recent change. Guest dkms was not installed before but now is dragged in as a depend of guest utils... What I don't understand is why pacman doesn't pull in linux headers as a dependency when installing anything which uses dkms. Will look into it in a bit and get it all fixed up. I haven't had a lot of time to work on arch anywhere lately but need to get a new release out for the may version of the iso. This issue will be resolved in the next release.

**Comment by faddat** [comment]
My recomendation:  Install DKMS by default.  I've found that everything that CAN use dkms, is more reliable if you DO use dkms

**Comment by deadhead420** [comment]
Issue resolved. I simply added linux headers. Next release 2.2.0 will be in just a few hours with vbox guest install working perfect will all desktops.
