### ISSUE TITLE
Can't add user on PL instalator

### ISSUE THREAD

**Issue by Pyton** [deadhead420/arch-linux-anywhere#334]
If I select Polish as Instalator language and other features for localization during add new User it shows me error.

Error comes from regexp which walidates username. 

After switch only Instalator language to EN it works ok.

**Comment by condor2** [comment]
I will test

**Comment by condor2** [comment]
Yep...something wrong with polish language...

**Comment by pnedkov** [comment]
#337 

Tested it once and it worked. Please give it a proper testing.

**Comment by condor2** [comment]
Yep it worked. Good job @pnedkov :+1:
