### ISSUE TITLE
Manual partition, incompatible with LVM

### ISSUE THREAD

**Issue by BakasuraRCE** [deadhead420/arch-linux-anywhere#338]
I will create an LVM system manually:

```
pvcreate /dev/sda3
vgcreate vgrooter /dev/sda3
lvcreate -n lvroot -L 30G vgrooter
lvcreate -n lvhome -l 100%FREE vgrooter
```

The device should look like this (sda1 for boot, sda2 swap, sda3 LVM):
![image](https://cloud.githubusercontent.com/assets/26231582/26029663/8ca3bdb4-3800-11e7-9986-c8d4c93ed92c.png)

Now I will start the installation wizard and go to the manual partition:
![image](https://cloud.githubusercontent.com/assets/26231582/26029675/ed013290-3800-11e7-88d8-d635b5fce18e.png)

I will select lvroot as mount point "/" (Edit vgrooterlvroot):
![image](https://cloud.githubusercontent.com/assets/26231582/26029680/3325f5e4-3801-11e7-9c42-2068b65c9c92.png)

Now you will see the error, the partition says "/dev/vgrooterlvroot", but it should be "/dev/vgrooter/lvroot"

And it will always produce this error:
![image](https://cloud.githubusercontent.com/assets/26231582/26029688/711e5ec2-3801-11e7-924c-a3d5f5a015b5.png)

**Comment by pnedkov** [comment]
The support for custom LVMs are on my TODO list for quite some time but I just don't have the time lately. What you are experiencing is a known issue. It will be implemented/fixed but I cannot provide you with any ETA.

**Comment by pnedkov** [comment]
#342 

I just managed to successfully install and boot with the following setup:
![screenshot_20170516_130137](https://cloud.githubusercontent.com/assets/6212427/26126715/925def76-3a3b-11e7-842a-cc2795968f5d.png)

I tested with grub.

**Comment by pnedkov** [comment]
booting from syslinux also works but it required one additional fix: #347

**Comment by BakasuraRCE** [comment]
Tested with grub. Fully functional.

![image](https://cloud.githubusercontent.com/assets/26231582/26226133/2b21b6e2-3bf0-11e7-9bb2-5818287ebc5e.png)

Thank you!

**Comment by BakasuraRCE** [comment]
Tested with GPT/EFI + Grub. works

![image](https://cloud.githubusercontent.com/assets/26231582/26228031/d3ecdce2-3bfb-11e7-8a29-762d688ed308.png)
