### ISSUE TITLE
How to use arch-anywhere-creator.sh?

### ISSUE THREAD

**Issue by MakuSensei** [deadhead420/arch-linux-anywhere#340]
Hi, sorry for my ignorance, I would like to know what the "arch-anywhere-creator.sh" file is, and how it is used

**Comment by Daylien** [comment]
Well first of all you need an Linux system. If you had, clone this repository. After that go into the cloned folder and open the terminal. Now type `sudo ./arch-anywhere-creator.sh`  And follow the screen instructions.

**Comment by MakuSensei** [comment]
Thanks, I just wanted to know what it was for

**Comment by condor2** [comment]
arch-anywhere-creator build Arch Anywhere ISO.
