### ISSUE TITLE
Won't Install Latest ISO...

### ISSUE THREAD

**Issue by CyberManifest** [deadhead420/arch-linux-anywhere#341]
I'm trying to install the latest ISO: arch-anywhere-2.2.7-2-x86_64.iso on a Virtual Machine using Virtual Box and I encounter the following issues:
<img width="596" alt="screen shot 2017-05-16 at 2 26 32 pm" src="https://cloud.githubusercontent.com/assets/22405699/26124793/5619479a-3a45-11e7-8e4e-0f93264f0864.png">
<img width="596" alt="screen shot 2017-05-16 at 2 27 11 pm" src="https://cloud.githubusercontent.com/assets/22405699/26124797/5b118596-3a45-11e7-9cd9-d18bd27976d1.png">
<img width="596" alt="screen shot 2017-05-16 at 2 27 54 pm" src="https://cloud.githubusercontent.com/assets/22405699/26124800/5d6b02a4-3a45-11e7-9a91-82147dd544b8.png">

**Comment by pnedkov** [comment]
fbterm 1.7.0-7 has been removed from the [community] repository.

This has been addressed with 80e4366da748691f94bc4088ced8981d2c5940ac

**Comment by condor2** [comment]
yep, I tell him on facebook group page :)
