### ISSUE TITLE
Installed system won't Boot (T470 NVMe SSD, no error)

### ISSUE THREAD

**Issue by ftes** [deadhead420/arch-linux-anywhere#356]
After installation on a Thinkpad T470 the system won't boot.
- apparently no boot partition is found (none listed in UEFI boot loader)
- happens for all boot loaders except EFISTUB (grub, systemd, syslinux etc.)
- happens both when UEFI is enabled or disabled in firmware

Workaround: select EFISTUB boot loader

**Comment by ftes** [comment]
Also, thanks for the great installer!

**Comment by ftes** [comment]
I submitted pull request #357 that adds an EFISTUB boot loader option.

This gives users a workaround.

**Comment by deadhead420** [comment]
Thanks for your contributions!

**Comment by ilazaridis** [comment]
I 've just got a T470p. Installation is completed successfully. `Arch Linux` shows up in the boot menu, but nothing happens (it goes back to the same menu). Any ideas ? @ftes @deadhead420

**Comment by ftes** [comment]
@ilazaridis Did you install in UEFI or BIOS/legacy mode?
An easy way to tell the difference: In BIOS mode the arch anywhere installer starts with a nice menu UI (some images in the background). In UEFI mode the menu is plain text.

**Comment by ilazaridis** [comment]
UEFI. Shall I try BIOS mode?

**Comment by ftes** [comment]
No, that's fine. Did you select the `EFISTUB` boot manager option?

If so, can you boot from the stick again and copy the output of `efibootmgr
-v`?

If that's too much of a hassle, try to re-do what the installer is trying
to do for you (if you selected EFISTUB).
Maybe there's a bug in the installer, and we can get it to work manually.
1. Delete the old Arch Linux entry in the efi boot manager
2. Add a new (hopefully now correct) entry

```
# 1. delete the old `Arch Linux` entry
# Replace `0` with the number of the `Arch Linux` entry you found by the
`efibootmgr -v`
efibootmgr -b 0 -B

# 2. Create new entry
# Make sure /dev/nvme0n1p1 is the partition where your EFISTUB system
partition lives (https://wiki.archlinux.org/index.php/EFISTUB#efibootmgr)

# EITHER 2a. For LVM LUKS encryption
efibootmgr -d /dev/nvme0n1 -p 1 -c -L "Arch Linux" -l \vmlinuz-linux
-u "cryptdevice=/dev/lvm/lvroot:root
root=/dev/mapper/root rw initrd=/initramfs-linux.img"

# OR 2b. Non-encrypted, set correct <linux-root-partition> (
https://wiki.archlinux.org/index.php/EFISTUB#efibootmgr)
efibootmgr -d /dev/nvme0n1 -p 1 -c -L "Arch Linux" -l \vmlinuz-linux
-u "root=<linux-root-partition>
rw initrd=/initramfs-linux.img"
```

**Comment by ftes** [comment]
No, that's fine. Did you select the `EFISTUB` boot manager option?

If so, can you boot from the stick again and copy the output of `efibootmgr
-v`?

If that's too much of a hassle, try to re-do what the installer is trying
to do for you (if you selected EFISTUB).
Maybe there's a bug in the installer, and we can get it to work manually.
1. Delete the old Arch Linux entry in the efi boot manager
2. Add a new (hopefully now correct) entry

```
# 1. delete the old `Arch Linux` entry
# Replace `0` with the number of the `Arch Linux` entry you found by the
`efibootmgr -v`
efibootmgr -b 0 -B

# 2. Create new entry
# Make sure /dev/nvme0n1p1 is the partition where your EFISTUB system
partition lives (https://wiki.archlinux.org/index.php/EFISTUB#efibootmgr)

# EITHER 2a. For LVM LUKS encryption
efibootmgr -d /dev/nvme0n1 -p 1 -c -L "Arch Linux" -l \vmlinuz-linux
-u "cryptdevice=/dev/lvm/lvroot:root
root=/dev/mapper/root rw initrd=/initramfs-linux.img"

# OR 2b. Non-encrypted, set correct <linux-root-partition> (
https://wiki.archlinux.org/index.php/EFISTUB#efibootmgr)
efibootmgr -d /dev/nvme0n1 -p 1 -c -L "Arch Linux" -l \vmlinuz-linux
-u "root=<linux-root-partition>
rw initrd=/initramfs-linux.img"
```
