### ISSUE TITLE
The Front Page of The Website Hasn't Been Updated In 4 Months

### ISSUE THREAD

**Issue by liamjc** [deadhead420/arch-linux-anywhere#358]
The title pretty much says it all. It's convenient to have info about the latest release right there, yet the front page currently talks about version 2.2.5, released 17th January.

**Comment by condor2** [comment]
I write here 2.2.7 changelog
https://arch-anywhere.org/forums/viewtopic.php?id=108

Dylan hi didn`t time to write news on for next release...2.2.6, 2.2.7 on website, but maybe will be for 2.2.8

**Comment by deadhead420** [comment]
I haven't had much time to work on the project lately. I'm back now to do a new release. The site will be updated when I do so.
