### ISSUE TITLE
Remove linux-*-headers packages

### ISSUE THREAD

**Issue by throwaway217** [deadhead420/arch-linux-anywhere#362]
With the default linux kernel the header packages aren't installed but with custom kernels they are.

**Comment by pnedkov** [comment]
linux-headers package is installed when you install `Arch-Linux-Base` or `Arch-Linux-Base-Devel`. Maybe you have not updated the installer?
`arch-anywhere -u`

**Comment by throwaway217** [comment]
I'm unsure if this is a case of retard blindness like my other issue but if you can't replicate this then that pretty much settles it. Thank you.
