### ISSUE TITLE
Pamac is once again outdated in AA repository.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#364]
Pamac 4.3.7 was released : see https://github.com/manjaro/pamac/releases/tag/v4.3.7 with a lot of new things : 

> fix issue with download of GPG keys (#260)
>     fix issue with reinstall-button for AUR packages (#228)
>     fix issue with keyboard shortcuts after installing packages (#244)
>     show build details only on failure
>     add Alt+Left (back) and Ctrl+F (search) keybindings
>     launch manager on left click on tray if no update
>     fix .files dl progress display
>     translations: update Catalan

**Comment by condor2** [comment]
Fixed

**Comment by FredBezies** [comment]
Thanks !
