### ISSUE TITLE
Unable to boot on Asus E200HA (Cherry Trail)

### ISSUE THREAD

**Issue by Daylien** [deadhead420/arch-linux-anywhere#367]
I try to install Arch on my Asus E200HA all work fine but it doesn't boot.

Timeout starts here:

`Jun 07 19:35:32 arch-netbook systemd[1]: dev-disk-by\x2duuid-D754\x2d7778.device: Job dev-disk-by\x2duuid-D754\x2d7778.device/start timed out.
Jun 07 19:35:32 arch-netbook systemd[1]: Timed out waiting for device dev-disk-by\x2duuid-D754\x2d7778.device.
-- Subject: Unit dev-disk-by\x2duuid-D754\x2d7778.device has failed`

Specs:  
> CPU: Intel Atom x5-Z8350 
> Ram: 2 GB DDR3L-RS 1600
> SSD: 32 GB SSD - (eMMC)

I also attach an Error log for better informations.

https://pastebin.com/VAxe33nS

**Comment by deadhead420** [comment]
I'm having trouble seeing how this has anything to do with arch anywhere... Your hostname is arch-netbook so clearly this is your own install. Also you posted an apache log... I would recommend checking the arch or apache forums. Good luck.

**Comment by liberodark** [comment]
Manjaro Work Great :D on this pc
