### ISSUE TITLE
[Arch-Anywhere Repository] Pacaur is out-of-date.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#369]
Hello.

Once again, pacaur is out-of-date. 4.7.9 was released on june 11, 2017.

See : https://github.com/rmarquis/pacaur/commit/6edab4d1eff4225e508e621a8b9ae38d95da6ace

**Comment by condor2** [comment]
Fixed

**Comment by FredBezies** [comment]
Thanks a lot.
