### ISSUE TITLE
No Headphone sound after suspend

### ISSUE THREAD

**Issue by DasJott** [deadhead420/arch-linux-anywhere#370]
Using Arch Anywhere with Deepin DE.

If my Tuxedo Laptop comes back from suspend all the audio jacks are dead. The internal speaker still works.

Audio device: Intel Corporation Sunrise Point-H HD Audio

Realtek ALC892

**Comment by pnedkov** [comment]
Do you experience the same problem when installing the system with the same software and configuration but **without** using the Arch Anywhere installer? I fail to see how this is a problem in the installer.

**Comment by DasJott** [comment]
I am sorry, I didn't think of this just being an installer. This clearly is a problem of the system and not the installer, I think.
