### ISSUE TITLE
Fetching mirrors.

### ISSUE THREAD

**Issue by oyger** [deadhead420/arch-linux-anywhere#379]
Hi.

I have been trying to install arch on my MS Surface pro 3 for some time now, and have lately found your Arch Anywhere.

I am having problems with the internet conection inside the installer. If I set up a manual config of netctl example wireless-wpa or when the installer prompt me for connecting using wifi-menu I am able to ping google.com and getting feedback.

But right after starting the installer and selecting either my country, US or default I get a message saying "Error: No network connection exiting installer." 

If i then ping google.com or any othe website I get feedback. If I test the ip connection with Iptest I am told that my network is working fine and i have a speed of 5Mb/s.

Do you have any Idea why this is occuring.

Oyger

**Comment by ivir** [comment]
Problem is with time. Before start installer try `ntpdate europe.pool.ntp.org`. Maybe also you should have a problem with integrity of package (PGP signature) then also before starting installer use `pacman-key --refresh-keys`. Then installation should be successful.

**Comment by oyger** [comment]
I managed to get around this problem about a day after I posted this issue by running pacstrap as instructed in the arch wiki, complete download to /mnt. And then running arch-anywhere.

As I have been trying to install arch the proper way and using arch and arch-anywhere together without much luck when comleting it with openbox I managed to do so today.
I am very happy to be on my newly installed system, but my keybord layout is a mess.

My /etc/vconsole.conf says that I am using no-latin1 but it responds only to US keymap.
Do you know why this is happening?

PS.
The pacman-key -init and then running pacman-key -populate worked best for me. I had no luck on just refreshing them.

**Comment by pnedkov** [comment]
`wget -q --spider https://github.com`

Does this work? This is how we test the internet connection.
