### ISSUE TITLE
Your site is down

### ISSUE THREAD

**Issue by RaymondSchnyder** [deadhead420/arch-linux-anywhere#380]
Title says it all.
arch-anywhere.org is down. 

maybe check your logs? :D

**Comment by derpyderpaderp** [comment]
I can confirm it is down for everyone checking via downforeveryone.

**Comment by oyger** [comment]
His site is up and running over here

**Comment by condor2** [comment]
Website was moved to another server. We working on it :)

**Comment by Code-Name-Debian** [comment]
Good to know.  Kept getting an error via Google Chrome

This site can’t be reached
arch-anywhere.org refused to connect.

Hope you resolve it soon.  Was going to seed the torrent file

**Comment by Gatgeagent** [comment]
Yes, it is still down, can confirm.

**Comment by derpyderpaderp** [comment]
Yet again down. Can we at least get a warning ahead of time?

**Comment by derpyderpaderp** [comment]
Is someone just learning to code XD "Hello world"

**Comment by azaydan** [comment]
can someone provide a magnet link to the lstest version of the torrent? i cant find anything after 2.2.2

**Comment by condor2** [comment]
See the link from pinned post

https://www.facebook.com/groups/archanywhere/

**Comment by Code-Name-Debian** [comment]
Facebook has removed your torrent as the link points to a pound symbol now # 
https://www.facebook.com/groups/archanywhere/#

**Comment by condor2** [comment]
Torrent is there :)

**Comment by katherinehackworth** [comment]
I'm assuming arch-anywhere.db is hosted with the site, and that's why the repo is down?

**Comment by condor2** [comment]
Website (SSL) is now UP

**Comment by Code-Name-Debian** [comment]
Website is up, but forum is still down as rewrite rules are not working

https://arch-anywhere.org/forums/ 

Will give you a Nginx error, however using the forum's true URL

https://arch-anywhere.org/forums/index.php

Will display the forum, but clearly, the forum's cache needs to be rebuilt as it only displays text

**Comment by Code-Name-Debian** [comment]
I have converted your torrent to a magnet link so that should the site go down and facebook remove your torrent from public view, it can still be seeded.

magnet:?xt=urn:btih:a253860adb0ce94623dbcfd9f559b232b4a98109&dn=arch-anywhere-2.2.8-x86_64.iso

**Comment by Code-Name-Debian** [comment]
Found out why your forum is not displaying

1) Rewrite rules are not correct

2)  You need to check your directory permissions (see error below)

An error was encountered
Error: Unable to write cache file cache_users_info.php to cache directory. Please make sure PHP has write access to the directory '/srv/arch-anywhere.org/htdocs/forums/cache/'.

**Comment by Code-Name-Debian** [comment]
502 Bad gateway
https://arch-anywhere.org/forums/index.php

At this point, if you want, send me a PM with the details, and I'll convert you to phpBB or NodeBB because clearly, your forum is not working and whoever is helping with your nginx config could learn a thing or two

**Comment by condor2** [comment]
Forum should work now :)
