### ISSUE TITLE
ctrl+a in 'AA-XFCE' desktop is mapped to a pull-down terminal

### ISSUE THREAD

**Issue by diffra** [deadhead420/arch-linux-anywhere#381]
This key combination is very commonly used for 'select all' and is not a good choice.

**Comment by deadhead420** [comment]
Thanks. Fixing now. I'm going to change a whole bunch of things on the desktop. I've been taking a long break from working on this project but am finally getting back to it.

**Comment by deadhead420** [comment]
This should be fixed. Its seems to only ever have been mapped to ctrl+~
