### ISSUE TITLE
Add possibility to rank or manually choose a mirror

### ISSUE THREAD

**Issue by julianxhokaxhiu** [deadhead420/arch-linux-anywhere#382]
Hi,

I am using your ISO to create some test VMs these last weeks. All is working fine, although to be honest, if I could have the option to choose a mirror manually ( from the one fetched after choosing the Country ) it would have faster my experience a lot.

Would it be possibile to add an option to ask for "Do you want to automatically choose a mirror using rankmirror?" and then if Yes, just continue the normal ranking process. If No, then allow the user to manually choose which line to uncomment.

What do you think? Would it be complicated to do?

Thank you and best regards,
Julian

**Comment by pnedkov** [comment]
#389 

Something like this?

**Comment by julianxhokaxhiu** [comment]
Yes! Exactly that :D Thank you!

When can I test the change?

**Comment by pnedkov** [comment]
You can test it right away. Just update the installer with:
`arch-anywhere -u`

**Comment by julianxhokaxhiu** [comment]
Nice, thank you!

**Comment by julianxhokaxhiu** [comment]
Hi there,

I tested the new functionality but actually it's not really helpful as the question is asked AFTER the ranking, while actually the manual editing is supposed to jump out of the ranking ( allowing you to not lose time, because of the time required by the ranking ).

Can you please fix it?

**Comment by pnedkov** [comment]
That is how I understood it and that is how I implemented it. You said you are satisfied and now you are not. I would rather wait 20-30 seconds than manually type a few URLs. Not only that but I would rather edit an already ranked (sorted) file than starting from scratch. To each their own. Let me see if I can improve it with minimal changes, but I am leaning towards the current implementation.

**Comment by julianxhokaxhiu** [comment]
I misunderstood your post then, I am really sorry. Although even if you read my first post it written like this:

```
Would it be possibile to add an option to ask for "Do you want to automatically choose a mirror using rankmirror?" and then if Yes, just continue the normal ranking process. If No, then allow the user to manually choose which line to uncomment.
```

The question now is a little different and the meaning of it is AFTER the ranking, while my request was to bypass exactly the ranking because you know already which mirror to use and you don't need to waste 30 seconds for nothing. That's the meaning of this issue :)

Thank you in advance again!

**Comment by deadhead420** [comment]
I've fixed it. Will be in next release

**Comment by julianxhokaxhiu** [comment]
Thank you!
