### ISSUE TITLE
Add possibility to choose which zshrc default file to have

### ISSUE THREAD

**Issue by julianxhokaxhiu** [deadhead420/arch-linux-anywhere#383]
Hi,

I've noticed that there is no possibility to choose which zshrc script is there by default.

Not that is bad what is given, but would be nice to have a choice to something like "None, Default, OhMyZsh". I guess whoever choose zsh, would definitely benefit from these three options.

Thank you and best regards,
Julian

**Comment by deadhead420** [comment]
I love zsh so I've added options for "Default" "oh-my-zsh" or "None". I've added oh-my-zsh to the arch anywhere repo so it will be installed if the user selects that option. I still have to test everything but it should be working good.

**Comment by julianxhokaxhiu** [comment]
Thank you! When will it be possible to be tested?

**Comment by FredBezies** [comment]
What about adding grml-zsh too? See #399 

I'm using it on a daily basis. By the way  @deadhead420, I have to reproduce your .zshrc from a brand new .zshrc file from oh-my-zsh. See #401 and #402 for more infos.

It won't work great with people speaking other locale than en_US.UTF-8.

**Comment by julianxhokaxhiu** [comment]
I tested the new setup process with Oh My ZSH, and I must say that the only missing step is copying the .zshrc file ( like the package "oh-my-zsh-git" suggests ) into the User(s) home directories.

At the current state this step is missing and even if you choose Oh My ZSH, you will not get it, but instead an empty zsh session that will ask you what to do as soon as you open the terminal with any of the users created during the setup process ( from root to any other one ).

Other than that, the package installation works fine :) Thanks, looking forward for this final fix!

**Comment by deadhead420** [comment]
Working as it should now. Release coming in a few hours

**Comment by julianxhokaxhiu** [comment]
Thank you! I'll try to test it later
