### ISSUE TITLE
Pamac 5.0.0 is out. Please update it :)

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#384]
Pamac-aur should be upgraded to version 4.9.0 : https://github.com/manjaro/pamac/releases/tag/v4.9.0

**Comment by FredBezies** [comment]
Not an official stable version of Pamac, tagged as prelease. Closing this issue until a new stable pamac is available. Sorry for bugspam :(

**Comment by FredBezies** [comment]
Reopening bug. Just in order to ask for Pamac-aur 5.0.0 update :)

https://github.com/manjaro/pamac/releases/tag/v5.0.0

**Comment by condor2** [comment]
Done
