### ISSUE TITLE
Zsh selection was not applied after installation.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#397]
After "fixing" bug #395,  I noticed oh-my-zsh wasn't setup by default. Looks like oh-my-zshrc wasn't copied. Weird.

Any idea?

**Comment by pnedkov** [comment]
You have to run `arch-anywhere -u` **twice**. The update functionality has been rewritten. The first executions of `arch-anywhere -u` uses the old implementation. This is why you have to run it a second time.

**Comment by FredBezies** [comment]
Ok. I will try again when zsh configuration bug is fixed :)

**Comment by FredBezies** [comment]
Tried again... No more luck, but at least, this is my step by step installation.

Installation with an ISO made from scratch and on latest git commit, so no need to update installer :)

1) language
2) mirrorlist step
3) no editing of generating mirrorlist file
4) keyboard
5) locale
6) timezone settings
7) automated partitionning
8) linux kernel + devel packages
9) zsh shell by default
10) oh-my-zsh selection :)
11) grub
12) network: networkmanager  
13) Multilib on
14) DHCP on
15) network utils: yes
16) PPPoE: no
17) os-prober: no
18) windows manager / desktop environment: yes
19) AA OpenBox
20) synpatics: no
21) Desktop Manager: LightDM
22) Additionals software: activated but nothing added
23) installation : oh-my-zsh-git is listed. Good :)
24) root password and add new user with sudo enabled
25) rebooted

When I opened a terminal... Classical zsh setup. By the way, the defined zshrc for oh-my-zsh needs to be modified in some parts: locales, harcoded path in it and some little bugs :(

**Comment by pnedkov** [comment]
I just pushed a fix. Could you please test it?

**Comment by pnedkov** [comment]
Please provide the following information:

1.

**Comment by FredBezies** [comment]
It works, but zshrc for oh-my-zsh needs a lot of tweaking:

![001](https://user-images.githubusercontent.com/8571419/29533646-12da852e-86b3-11e7-85e1-9f521dfc72f3.png)

Opening a new bug for it :)
