### ISSUE TITLE
When installing in EFI with grub, file in /boot/EFI/boot is misnamed.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#400]
I was trying to do some beta-test for Arch-Anywhere 2.2.9 with VirtualBox and EFI enabled.

I noticed I cannot boot my ArchAnywhere virtual machine after shutting it down. After getting it back to boot, I saw that instead of /boot/EFI/boot/bootx64.efi I had /boot/EFI/boot/grubx64.efi

Renaming file fixes this PITA bug.

I wonder why file was not rightly copied :(

**Comment by pnedkov** [comment]
Here is what the code does:
`mv "$ARCH"/"$esp"/EFI/boot/grubx64.efi "$ARCH"/"$esp"/EFI/boot/bootx64.efi) &> /dev/null`

From [here](https://wiki.archlinux.org/index.php/GRUB):

> Some UEFI firmwares require a bootable file at a known location before they will show UEFI NVRAM boot entries. If this is the case, grub-install will claim efibootmgr has added an entry to boot GRUB, however the entry will not show up in the VisualBIOS boot order selector. The solution is to place a file at one of the known locations. Assuming the EFI partition is at /boot/efi/ this will work:
`mkdir /boot/efi/EFI/boot`
`cp /boot/efi/EFI/grub/grubx64.efi /boot/efi/EFI/boot/bootx64.efi`
This solution worked for an Intel DH87MC motherboard with firmware dated Jan 2014.


Notice how on the wiki they are copying the file. We on the other hand move it. Could you please change `mv` to `cp` in the command above and test it? I will not creating a pull request for such a small change. It is pretty self explanatory. I will commit and push once we have a positive result. Thanks.

**Comment by FredBezies** [comment]
Well... I tried replaced mv by cp, and I only have grubx64.efi in /boot/EFI/boot...

Weird. Looks like there is something wrong here, but what... Can't say. What $esp stands for? /boot?

Looked at scripts and did not find it... Or was I looking at the wrong place?

**Comment by FredBezies** [comment]
I tried it. Doesn't work.

I will try to copy the file without renaming it and then doing a mv to name it correctly. Kinda dirty, but why not?

**Comment by FredBezies** [comment]
Even with this trick, I cannot get it to be renamed :(

```
cp "$ARCH"/"$esp"/EFI/boot/grubx64.efi "$ARCH"/"$esp"/EFI/boot/grubx64.efi
mv "$ARCH"/"$esp"/EFI/boot/grubx64.efi "$ARCH"/"$esp"/EFI/boot/grubx64.efi) &> /dev/null &
```
Or am I doing something wrong? Well... I do hate UEFI and grub2 :D

**Comment by FredBezies** [comment]
Just an idea. What will happen if cp line became this ?

cp "$ARCH"/"$esp"/EFI/$esp_mnt/grubx64.efi "$ARCH"/"$esp"/EFI/boot/grubx64.efi

We'll try this asap.

**Comment by pnedkov** [comment]
Try this:

`cp "$ARCH"/"$esp_mnt"/EFI/boot/grubx64.efi "$ARCH"/"$esp_mnt"/EFI/boot/bootx64.efi`

**Comment by FredBezies** [comment]
It works. Now, testing mv command to see if I can only have one efi file.

Yes! Nearly fixed, now.

**Comment by pnedkov** [comment]
Cool. Let me know and I will commit the change.

**Comment by FredBezies** [comment]
mv works too. With cp, you have both grubx64.efi and bootx64.efi.

So, your idea worked. Another bug bites the dust :)

**Comment by pnedkov** [comment]
Just pushed the fix. Feel free to close the issue.
