### ISSUE TITLE
oh-my-zsh rc file needs some tweaking.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#401]
Following bug #397, you'll need to tweak the rc file provided.

1) There is no /home/dylan/.oh-my-zsh/oh-my-zsh file
2) hardcoding a locale is not a good idea.
3) in line 56, there is source $ZSH line...

See attached screenshot: 

![virtualbox_aa 2 2 9_21_08_2017_20_57_00](https://user-images.githubusercontent.com/8571419/29534005-9ed9c1c4-86b4-11e7-9464-7b16e66cede4.png)

**Comment by pnedkov** [comment]
I just fixed that. But I have no idea where the directory ~/.oh-my-zsh is supposed to come from. I have no experience with zsh let alone oh-my-zsh. Someone who is using that thing should fix it.

**Comment by FredBezies** [comment]
What about taking a blank zshrc file from oh-my-zsh and modified it to set it to bureau theme ?

Just guessing :)

**Comment by FredBezies** [comment]
Using /usr/share/oh-my-zsh/zshrc and set zsh theme to bureau.

Here is the result:

![virtualbox_aa 2 2 9_21_08_2017_21_23_16](https://user-images.githubusercontent.com/8571419/29534647-01808798-86b7-11e7-86f4-b28276dfac23.png)

**Comment by pnedkov** [comment]
So, what would be the fix then? If I change:
`export ZSH=~/.oh-my-zsh`
to
`export ZSH=/usr/share/oh-my-zsh`

in `extra/.zshrc-oh-my`, will this fix it?

I really do not want to touch this because as I said I don't use zsh. If you fix it and create PR I will merge it.

**Comment by FredBezies** [comment]
It will partly fix the bug. You have to comment line 56 and the line with en_US.UTF-8 too. Here is the first part you can at least commit this.

I will work on a bigger patch on zshrc on tuesday. Sorry for this step by step fix :D

**Comment by pnedkov** [comment]
I will stay out of this. IMO such environment tweaks should not be in any installer in the first place.

**Comment by FredBezies** [comment]
@pnedkov of course. Don't worry. I will work tonight on this file. Starting from a blank new .zsrhrc from oh-my-zsh, tweak it to make it look like the one provided by arch-anywhere and provide you a patch you can apply.

Stay tuned :D

**Comment by FredBezies** [comment]
Result with a tweaked zshrc from oh-my-zsh from scratch and making it a copy of arch-anywhere one: 

![virtualbox_aa 2 2 9_21_08_2017_22_19_02](https://user-images.githubusercontent.com/8571419/29536768-55de6726-86bf-11e7-986e-95965cff9080.png)

Will propose a patch soon on current arch-anywhere zshrc you can apply (or remove) easily.

**Comment by FredBezies** [comment]
Not a lot of work, but at least, it seems to work better :)

**Comment by FredBezies** [comment]
Fixed. Done a full install from scratch and this bug is dead. Thanks for your help!
