### ISSUE TITLE
Lamp

### ISSUE THREAD

**Issue by fumseck** [deadhead420/arch-linux-anywhere#409]
Thanks for your installer, can you add lamp in installation select software ?
lamp ) apache mariadb and php

it's will be useful i thinks

**Comment by deadhead420** [comment]
That is a really good idea. As of now I think I've only included apache. I will add an option to install the full LAMP stack. I think I might also add an option for the LEMP stack (nginx / sql / php)

**Comment by fumseck** [comment]
yes, it's a good idea

**Comment by deadhead420** [comment]
The next release will feature a "server" menu in additional software. It includes options to install fully configured LAMP or LEMP stack. Also includes ssh, mail server, dns server, apache, nginx, and lighthttpd, web cache server, and a few other things. Thanks for giving me the idea, this is very useful as users will now be able to have a fully enabled LAMP or LEMP stack out of the box. Look for it in the next release.

**Comment by fumseck** [comment]
thanks
