### ISSUE TITLE
oh my zsh

### ISSUE THREAD

**Issue by fumseck** [deadhead420/arch-linux-anywhere#410]
I've installed the zsh shell with the oh-my-zsh configuration by default, i've not the .zshrc in my home directory i'm obliged to clone repository and install it. 

it's possible this bug comes from me .

regards

**Comment by deadhead420** [comment]
Sorry about that. I didn't test that feature before I pushed it. Will fix it now and let you know

**Comment by fumseck** [comment]
it's ok i wanted say this problem to help you

**Comment by deadhead420** [comment]
Thank you for pointing it out. All zsh configurations are working as they should be now. I will be doing a release in the next few hours.

**Comment by fumseck** [comment]
thanks
