### ISSUE TITLE
Translation lines are missing for server software section...

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/arch-linux-anywhere#416]
Testing git version of AA 2.2.9 (it is wonderful to be able to add cups !), but I noticed there is no translation lines added for server software list section... Ouch!

**Comment by deadhead420** [comment]
What do you mean?

**Comment by deadhead420** [comment]
Can you point out which lines are missing?

**Comment by FredBezies** [comment]
All srvX ones like the one Condor added in romanian translation: 

### Server
srv1="Apache-MariaDB-PHP"
srv2="Nginx-MariaDB-PHP"
srv3="Nginx HTTP/Proxy Server (Stable Branch)"
srv4="Nginx HTTP/Proxy Server (Latest Branch)"
srv5="Light Flexible HTTP Server"
srv6="Server email"
srv7="Server FTP"
srv8="Full-featured Web proxy cache server"
srv9="SMB Fileserver and AD Domain server"
srv10="The ISC DNS Server"
srv11="The CUPS Printing System"
sys1="Apache"
sys10="OpenSSH"

**Comment by condor2** [comment]
All software descriptions is in arch-anywhere.conf.

If you want to translate descriptions in you language, you need to add in you language file :)

**Comment by FredBezies** [comment]
My bad. Closing this bug with a brown paper bag on it :D

**Comment by deadhead420** [comment]
No problem. I add those to arch-anywhere.conf because it would be too time consuming for me to manually add them to each translation. Feel free to add them to your translation if you'd like

**Comment by FredBezies** [comment]
@deadhead420 I will track arch-anywhere.conf now. By the way, I just added about... 25 lines to french translation. Verifying them now. Will add a patch within an hour.

I forgot: thanks a lot for adding cups. I was going to ask for it :)

**Comment by condor2** [comment]
Just added Server translations at the beginning, moved translated lines where belong :)

**Comment by FredBezies** [comment]
I saw that ;)

**Comment by deadhead420** [comment]
@FredBezies final language update for 2.2.9 is complete. I should be done adding lines to translations now

**Comment by FredBezies** [comment]
Translated :D
