### ISSUE TITLE
2.2.9 soon ?

### ISSUE THREAD

**Issue by 3kynox** [deadhead420/arch-linux-anywhere#418]
Looks like we will have an update soon on website ? :)

Correspond to the exact time when I am re-installing my machine.

**Comment by deadhead420** [comment]
Very soon. I expect within 2-3 hours if all goes well and so far all has gone very well.

**Comment by 3kynox** [comment]
Very kool. I will be able to see it once done on website I suppose ?

**Comment by deadhead420** [comment]
Yes I'm starting the process now. I'll close this issue when its released.

**Comment by 3kynox** [comment]
You guys rocks :)

**Comment by deadhead420** [comment]
Its ready to download I just haven't changed the link on the site or announced it yet because I want to download and test it first. Feel free to dive in:

Torrent: https://arch-anywhere.org/iso/arch-anywhere-2.2.9-x86_64.iso.torrent

Direct: https://arch-anywhere.org/iso/arch-anywhere-2.2.9-x86_64.iso

**Comment by 3kynox** [comment]
Thank you ! Well done - Installing :)

**Comment by 3kynox** [comment]
Reopen here, can't get 2.2.9 script running.

I tried burn two different USB keys using DD / ISO method with Rufus : 
- MBR for BIOS or UEFI
- GPT for UEFI

I boot correctly on the key in UEFI mode and when boot completed and I type 
# arch-anywhere

I have the blue / grey screen with the cursor and script do not load.

I don't know what's going on

**Comment by condor2** [comment]
Can you post a screenshot?
Check if the checksums are the same
Try different flash drive

**Comment by 3kynox** [comment]
I tried with two stick and prior connected to my wlan using wpa_supplicant and ran first a 

```$ arch-anywhere -u```

Ran after arch-anywhere and after a few moment I get this : 

![](https://i.imgur.com/u37gUPn.jpg)

**Comment by condor2** [comment]
Maybe this help you
https://github.com/deadhead420/arch-linux-anywhere/issues/344

**Comment by pnedkov** [comment]
I have seen this before. This guy had the same problem and there is a work-around: #344

**Comment by 3kynox** [comment]
Thanks for update, here is a small status. I commented all if .. elif .. where script check if it's $VM or not and where lspci is called just after. Result -> I was able to install minimal arch (no wm / extra packages) but same problem using lspci command or reboot / shutdown which hangs indefinitely.

I'll have to repare that soon.

**Comment by 3kynox** [comment]
Thanks anyway ! My new arch installed. I for now let nouveau blacklisted and I will : 

- Repare it and try to find further what's going wrong exactly
- Install Bumblebee with  xf86-video-intel & NVidia proprietary driver

Closing here and will contribute a little later (french translation / bspwm more Advanced wm installation).

Cheers :)
