### ISSUE TITLE
Installer - Issue loop on "user edit" 

### ISSUE THREAD

**Issue by nt-jjrubio** [deadhead420/arch-linux-anywhere#433]
If edit user into install script to change password, installer enter on loop (When press back, goto Set Full Username)

**Comment by condor2** [comment]
what language?

**Comment by m00nyONE** [comment]
same for me in german

**Comment by condor2** [comment]
Possible a bug/missing line in German language.

**Comment by nt-jjrubio** [comment]
sorry for not answering in time, I fail in Spanish

**Comment by condor2** [comment]
You have updated script before?

**Comment by nt-jjrubio** [comment]
I try with latest iso arch-anywhere-2.2.9-x86_64.iso and fails.
md5sum iso: f503c93d4e95207f0a1931483434aef1  arch-anywhere-2.2.9-x86_64.iso

**Comment by condor2** [comment]
You have updated script before start installer??

**Comment by nt-jjrubio** [comment]
Ok, now works,  Thanks and good job for all installer ;)
