### ISSUE TITLE
SSL arch-anywhere.org certificate expired

### ISSUE THREAD

**Issue by optio50** [deadhead420/arch-linux-anywhere#452]
During Install SSL arch-anywhere.org certificate expired

Install halted at this point

**Comment by FredBezies** [comment]
You cannot chose any package from arch-anywhere repository too, even a customized version of zsh besides default one.

**Comment by pnedkov** [comment]
Please disable Arch Anywhere repo until the certificate gets renewed. That is the thing with the certificates issued by Let's Encrypt CA - they are only valid for 90 days. This problem can be addressed by automating the process of renewing the certificate so this does not ever happen.

**Comment by condor2** [comment]
Should work now :)
