### ISSUE TITLE
add AUR helpers

### ISSUE THREAD

**Issue by pvinis** [deadhead420/arch-linux-anywhere#49]
it would be cool to have a section to install AUR helpers, like where you choose text editors, games etc.

I use `pacaur` very much and `pm` before it.

**Comment by faddat** [comment]
I'm more if a yaourt guy and would love having all three.  Let me know if I can assist with anything, freaking love arch anywhere.

**Comment by deadhead420** [comment]
added in the next release

**Comment by jonocodes** [comment]
I installed anywhere 2.2.5 today and it did not install yaourt. 

I would like access provided to the AUR, but please provide instructions how to get it. 
Perhaps in the readme? Or as an install option like Antergos does it?

I see it in your repo online, but I had to install it manually.

Thanks.
