### ISSUE TITLE
Syslinux to / (root partition)

### ISSUE THREAD

**Issue by spsf64** [deadhead420/arch-linux-anywhere#56]
Hi @deadhead420 ! I don't know if you noticed my reply at:

https://github.com/deadhead420/arch-linux-anywhere/issues/28#issuecomment-228544019

I checked the latest (as of today) arch-installer.sh and did not see any option to install syslinux to root partition instead of mbr...

The command would be: "syslinux-install_update -i" (instead of -iam).
Can you check if it is possible to add such option?

TIA

**Comment by deadhead420** [comment]
Simply use manual partitioning and make one root partition. Syslinux will be installed on the root partition... Adding this feature would just add another menu and isn't useful enough. This is simple enough to be done by the user in a chroot after the install "Arch Anywhere Chroot".
