### ISSUE TITLE
select /dev/sdx?? as target partition -> truncated to /dev/sdx?

### ISSUE THREAD

**Issue by TheRealMarnes** [deadhead420/arch-linux-anywhere#57]
When the installer asked to select my root partition during manual partition setup, I selected sda11. The steps after that showed sda1 as my supposed selection instead of sda11.

I didn't continue after that to see if it's "just" a display bug or if it really truncates my selection to single digits, because I didn't feel like potentially wiping my efi partition...

**Comment by deadhead420** [comment]
Hey man. Thanks for pointing this out. This is a bug. I've got it fixed and will close this issue at the next release

**Comment by deadhead420** [comment]
Going to close this now. Has been fixed in 2.2.3 am about to release in a few hours.

**Comment by TheRealMarnes** [comment]
Ok, thanks
