### ISSUE TITLE
feedback: keymap, language pack

### ISSUE THREAD

**Issue by phenri** [deadhead420/arch-linux-anywhere#59]
I just tried the installer and I am very satisfied with the ease of installation. Really good job. Thank you.

I just have a few suggestions. The first is to define the keyboard layout from the first start page because not obvious to non-qwerty keyboard. (ie **F2, F3** in Manjaro v0.8.2 at boot dvd)

![](https://wiki.manjaro.org/images/0/05/0.png)

The second suggestion would be to add languages ​​packs for some selected software (firefox, thunderbird, libreoffice, etc) depending on the chosen language.

The third is still for the keyboard layout. In the Desktop Environment (here XFCE) keyboard is not defined and is still US. The following command fills this gap: `setxkbmap -layout fr`
We can retrieve the list of **model, variant, layout** and **option** of the command `setxkbmap` in `/usr/share/X11/xkb/rules/evdev.lst`

Voilà for the feedback.

**Comment by deadhead420** [comment]
Hey.
Thanks for pointing this out. I had been setting the keymap in /etc/vconsole.conf which is obviously only for the virtual console. I've added the setxkbmap command to run when the user installs a desktop. This will be fixed in the next release. Thanks again!
