### ISSUE TITLE
Cannot install via proxy

### ISSUE THREAD

**Issue by schlamar** [deadhead420/arch-linux-anywhere#61]
I have set a proxy via http_proxy/https_proxy environment variables, but the installer script is ignoring them und does not connect to my proxy (I used Fiddler as MITM proxy to debug the connection).

Is there another way to configure the proxy?

BTW, guides on your homepage are not available.

**Comment by deadhead420** [comment]
hmmmm..... good question.... Not too sure on this one... Only thing I can think of is maybe pacman needs to be configured to use a proxy? Have you installed arch linux manually using a proxy?

**Comment by schlamar** [comment]
Yes, manual install did work out of box (with environment variables). Are
you doing the internet connection check on your own? I assume that is
broken...

Am 27.08.2016 18:29 schrieb "deadhead" <notifications@github.com>:

**Comment by deadhead420** [comment]
The internet connection check simply consists of me using wget to download a 1MB test file. The download speed is displayed in the wget.log so I am able to check the users speed. Not sure if that has anything to do with it.... My guess would be for some reason my script isn't reading the env vars. Did you use export when you set the variables? You could try adding the variables to the configuration file for arch-anywhre:

/etc/arch-anywhere.conf

can add them in at the top like so:

export http_proxy=xxxxx
export https_proxy=xxxxx

Save the file then try running the installer. It reads all the variables from the config at the beginning of the install.

**Comment by deadhead420** [comment]
If this works for you I would be glad to add an option to install via proxy. For example:

arch-anywhere -p
arch-anywhere --proxy

**Comment by schlamar** [comment]
Oh, your test link was using ftp. Looks like the file is down but otherwise `export ftp_proxy=...` should have worked. Changing the test link works for me, though.
