### ISSUE TITLE
Option to use Manjaro repos instead of Arch repos

### ISSUE THREAD

**Issue by Limdel** [deadhead420/arch-linux-anywhere#63]
I just tried installing Arch Anywhere replacing Arch repos with Manjaro repos, and it went pretty smooth. What would be super awesome though, if there would be builtin feature to switch between Manjaro and Arch repos, without manually editing pacman.conf. Yes, I know that Manjaro have NET install, but it actually installs some unneeded bloat and anyway Arch Anywhere is much better in general, and this option shouldn't be hard to implement.

**Comment by deadhead420** [comment]
Cool idea but I can see problems coming out of it and not enough people would use it to make it a feature. After all this is arch anywhere. not manjaro anywhere. haha ;) But still cool idea and glad it worked okay for you
