### ISSUE TITLE
Add support for systemd-boot

### ISSUE THREAD

**Issue by wsxarcher** [deadhead420/arch-linux-anywhere#66]
systemd-boot is stable and simple

**Comment by clairem93** [comment]
oh god yes please +1

**Comment by Iljitsch** [comment]
id like it really +1

**Comment by Xyllon** [comment]
Yes please, +1.

**Comment by amalikmichael** [comment]
+1, please

**Comment by deadhead420** [comment]
Due to popular demand I've added systemd-boot into the next version 2.2.4. It only supports EFI since its BIOS support is very limited. This feature will be in the next release in just a few days.
