### ISSUE TITLE
Cannot start installer on MacBook

### ISSUE THREAD

**Issue by justanotherjason** [deadhead420/arch-linux-anywhere#68]
Hello there, thank you very much for this awesome tool. After trying it in a virtual environment I decided to test it on my macbook, unfortunately several issues pop up and I can't even start the installation process.  Everything worked perfectly whilst using virtual box so not really sure what the problem is.

I have burned the ISO to a USB flash drive using # dd if=arch-anywhere-dual.iso of=/dev/sdX bs=4M && sync and consulting the arch wiki page at https://wiki.archlinux.org/index.php/USB_flash_installation_media#In_macOS so I am pretty sure that the USB was correctly prepared. I tried twice by redownloading the iso but the same issues occur.

The first issue is exactly the same as https://github.com/deadhead420/arch-linux-anywhere/issues/48 but I managed to fix it either by using grub or mv to rename the iso label to ARCH_201609 since it is originally labelled as ARCH_EFI. Once I hit exit (to logout from rootfs) I get another problem but I have no idea how to proceed... The installer seems to be unable to locate the airootfs.sfs file.

something like losetup: /run/archiso/bootmnt/arch/.../airootfs.sfs: No such file or directory
:: Mounting '' to '/run/archiso/sfs/airootfs'
Waiting 30 seconds for device ...
ERROR: '' device did not show up after 30 seconds...

When I was dropped into roofs for the second time I tried searching for the missing file in an attempt to move it to where the installer is searching for it but I could not locate it.

Any pointers would be greatly appreciated.

Thanks

**Comment by d4l3k** [comment]
I fixed it by running `mv /dev/disk/by-label/aaiso2 /dev/disk/by-label/ARCH_201609`. Renaming `ARCHISO_EFI` to `ARCH_201609` results in the error you describe.

**Comment by condor2** [comment]
Bug fixed
