### ISSUE TITLE
LTS kernel with LVM issues

### ISSUE THREAD

**Issue by Teejer** [deadhead420/arch-linux-anywhere#72]
I've ran into an issue when selecting base-lts with encrypted LVM. The LTS kernel isn't built correct, it doesn't appear to include what it needs for encrypted volumes. Also the 100mb /boot partition is too small. I've ran out of disk space on that partition.

I've changed the 100m in /usr/bin/arch-anywhere to be 1024m. This fixes the /boot partition. I still can't boot up with the LTS kernel though. To fix this I've logged in with the failback boot option which boots into the normal 4.7 kernel then pacman -S linux-lts linux-lts-headers and then I can boot with the LTS kernel.

**Comment by deadhead420** [comment]
Thanks for the report. This should be addressed in the next release. I've made the default size of boot 512 when using LVM (should be more than enough). I've also added the kernel headers to the install for lts. This should take care of any issues. Will be released in a few days with 2.2.4.
