### ISSUE TITLE
Menu blank in pt_BR

### ISSUE THREAD

**Issue by frnogueira** [deadhead420/arch-linux-anywhere#73]
On this option bellow, in brazilian portuguese he is blank.

![captura de tela de 2016-09-29 11-53-57](https://cloud.githubusercontent.com/assets/2768725/18959634/46309778-863d-11e6-8139-046950c11851.png)

Only the YES and NO buttons appers.

**Comment by deadhead420** [comment]
Thanks man! Forgot to add this line to translation. Will fix it first thing
when I get home.

**Comment by frnogueira** [comment]
Great, my friend!

**Comment by deadhead420** [comment]
Should be in about 2 hours. Will close this issue when its fixed so you can
translate from English.

**Comment by frnogueira** [comment]
Done!
