### ISSUE TITLE
/dev/disk/by-label/aaiso2 timeout

### ISSUE THREAD

**Issue by TheInitializer** [deadhead420/arch-linux-anywhere#76]
I'm having an issue sort of like #48 but it's looking for a drive with the label aaiso2. Of course, drive labels can only have uppercase letters, no lowercase, so it's looking for an invalid label. Renaming it to AAISO2 doesn't work. I used LinuxLive USB creator to flash.

How can I fix this?

**Comment by dahjin** [comment]
Im having the same problem here

**Comment by Xyllon** [comment]
Right so before it's fixed, what you have to do is hit "e" when it's in the bootloader (or whatever it's called), scroll right to the end using arrow keys and you can change it from aaiso2 to AAISO2.

**Comment by JosephCW** [comment]
^ Above worked as a fix. 
When you first boot into the system and you are on [this screen](https://camo.githubusercontent.com/00c2645b16f54d4822f3ed495d5c3a9b1dc7ed4b/687474703a2f2f617263682d616e7977686572652e6f72672f696d616765732f617263682d616e7977686572652d73706c6173682e706e67) you just hit the the 'e' key. Then hit the end button or arrow key over and change the text to your drive label. Once changed just hit enter and it will launch right up. Thanks.

**Comment by condor2** [comment]
I changed label from lowercase to upercase.

**Comment by deadhead420** [comment]
This has been fixed for the next release coming soon
