### ISSUE TITLE
Menu destroyed in Virtual Machine Manager

### ISSUE THREAD

**Issue by anoxi** [deadhead420/arch-linux-anywhere#80]
ISO version: 2.2.3

Menu is destroyed with log output in Virtual Machine Manager on QEMU/KVM and Ubuntu 16.10. host.

![screenshot from 2016-11-17 21-54-42](https://cloud.githubusercontent.com/assets/2816367/20407566/2dc3973e-ad12-11e6-80cb-7c7fbff6d061.png)

**Comment by deadhead420** [comment]
I don't believe this issue is present in the latest ISO... Going to close issue for now. If this problem presists when using an updated ISO please re-open issue. Thanks
