### ISSUE TITLE
Syslinux unable to boot from MBR / BIOS

### ISSUE THREAD

**Issue by spsf64** [deadhead420/arch-linux-anywhere#81]
I just did a new install from latest iso and noticed syslinux was not there…
I used it to install the boot loader to system partition, browsing your code I found:

### If anyone can figure out how to get this working again be my guest…

I found this in syslinux page: 
http://www.syslinux.org/wiki/index.php?title=Filesystem

`As of Syslinux 6.03, "pure 64-bits", compression and/or encryption are not supported.

Quoting part of the release notes of version 1.43 of e2fsprogs (May 17, 2016):
Mke2fs will now create file systems with the metadata_csum and 64bit features enabled by default.
Users should rather (manually) disable the 64bit feature in the mke2fs command when creating / formatting a boot volume with ext4; otherwise, the bootloader (as of version 6.03) will fail.
Notes:
For a 4KiB block size, an ext2/3/4 volume size of less than 16TiB when created without the "64bit feature" is supported by Syslinux as of version 6.03.
To manually disable the "64bit" feature when creating ext4 volumes, use  -O ^64bit  in the mke2fs (or equivalent) command. That is, an upper-case letter "O", a space character, the caret "^" symbol, followed by "64bit" (no hyphen).
In some cases, a backslash character before the caret might be needed:  -O \^64bit `

Also noticed that gparted use this flag when formatting a new partition, so maybe this is the problem with syslinux unable to boot from MBR??

Another question, is it possible to add an option to install grub to system partition instead of MBR?

**Comment by condor2** [comment]
Same code was used on 2.2.2 and syslinux worked :)

**Comment by condor2** [comment]
After some testing syslinux work only if /root, /boot has  bootable flag.

**Comment by deadhead420** [comment]
Fix has been made. Syslinux is now working with bios boot. Simply had to add -O ^64bit to disable 64 bit volume support on boot partition. Will be fixed in 2.2.4 releasing soon
