### ISSUE TITLE
The current iso does not work

### ISSUE THREAD

**Issue by mateuscfonseca** [deadhead420/arch-linux-anywhere#87]
Please generate a new .iso, i am on ubuntu so i cant use your scripts

In the begging of the process it trys to mount something hangs 30 seconds then fails, i think the last updates will correct this problem

**Comment by mateuscfonseca** [comment]
![photo_2016-11-29_19-13-24](https://cloud.githubusercontent.com/assets/2181331/20729148/fbdeeac0-b667-11e6-93b6-401dc300446d.jpg)

**Comment by condor2** [comment]
What ISO is this? on Label write 201609 and label for Arch Anywhere is aaiso2.

**Comment by mateuscfonseca** [comment]
I had  to change the label because it was failing to mount the device, I saw on the Internet people saying to change the label. 

The iso is the latest one from your website, from September. 

I use dd to create the bootble USB. 

I noticed that my first screen is different from your YouTube tutorial and it is that same as the original arch iso. 

Will try a new flash drive

**Comment by foorb** [comment]
Similar here with a Virtual Machine:
<img width="754" alt="bildschirmfoto 2016-12-07 um 14 28 57" src="https://cloud.githubusercontent.com/assets/14993807/20969502/7ef94898-bc89-11e6-9ca2-9ac59332caf8.png">

**Comment by condor2** [comment]
in VirtualBox?

**Comment by foorb** [comment]
I think its Qemu/KVM on my VPS provider.

**Comment by condor2** [comment]
Tested 2.2.3 in QEMU Arch Linux. Boot without problem.

**Comment by foorb** [comment]
Are there any further Information I can provide to you?

**Comment by bmentink** [comment]
This is an issue for me as well .. someone needs to test this on a real machine, NOT an emulator!

**Comment by deadhead420** [comment]
This is a disk label issue. Has been fixed and will be released in the new ISO in the next day or two.

**Comment by jth005** [comment]
This issue is still present in version 2.2.4

**Comment by deadhead420** [comment]
Can you please describe the issue you're having? Blank screen, no boot, label issue? Need more detail. I have not encountered any issues with booting on 2.2.4. I've tested on 4 real systems also in vbox, vmware, qemu.

**Comment by deadhead420** [comment]
Also how did you create your install media?

**Comment by jth005** [comment]
I tested on a Dell Latitude e7240. It's boots partially, but I'm running into a similar labeling issue. I created the media with dd, but I've also tried gnome-disks.
![img_20170104_121219](https://cloud.githubusercontent.com/assets/1507619/21653671/483dea4a-d280-11e6-9e44-bd8334f49523.jpg)

**Comment by deadhead420** [comment]
Are you using EFI or BIOS boot?

**Comment by jth005** [comment]
I'm using EFI.

**Comment by deadhead420** [comment]
It shouldn't be doing that... Looking into it now. When you boot up. At the bootloader where it says Arch Anywhere ISO x86_64 UEFI. At that boot menu press 'e' before it times out. Then scroll over to the right at the end it says 'ARCH_201701' change it to to 'AA224' and press enter, it should boot

**Comment by bmentink** [comment]
The problem still exists for EFI boots ... as I also reported some time
back...

**Comment by deadhead420** [comment]
Looking into it but have tested many times and have never seen this happen. I'm downloading the latest ISO from the site, only thing I can think of is its an issue with that build. The builds which I've tested have all been created local. The current ISO build was created on the server (but using exact same script as local builds) and I have not yet tested it. It has to do with the label in the efi loader config, I have a line in the creator.sh script which uses sed to change the label from ARCH201701 to AA224 as the label for the ISO is AA224. If the label is not changed in the EFI loader conf that is the only thing I can think of which would cause this issue, however like I said the label is changed automatically by the script so I'm really not sure why this would happen... I'll get to the bottom of it. As I said the build on the server might not have changed the label in the EFI config for whatever reason

**Comment by deadhead420** [comment]
Finally figured it out. Fix will be released soon

**Comment by deadhead420** [comment]
I've figured it out. Did a hex dump to change the binary data in the img file, everything should be working now. I'm doing a release with the fix soon.
