### ISSUE TITLE
DM choice instead of only lightdm

### ISSUE THREAD

**Issue by TheRealMarnes** [deadhead420/arch-linux-anywhere#89]
I'd like to request the display manager to be chooseable, like the DE is. sddm is the one I miss most, but I guess others should be included too if possible/reasonable. I'm not a pro on the linux ecosystem so I'm not sure which are good choices.

**Comment by condor2** [comment]
for now, sddm can be installed only with plasma :)

**Comment by deadhead420** [comment]
I've added 3 more display managers for the next release. Can now choose from gdm, lightdm, lxdm, and sddm. Will be doing a release soon 2.2.4
