### ISSUE TITLE
Virtualbox Intel PRO/1000 MT Desktop Adapter produces errors

### ISSUE THREAD

**Issue by mrrabinhalder** [deadhead420/arch-linux-anywhere#92]
I installed Arch Linux base using Arch Linux Anywhere installer. But, post successful boot, the VM produces errors indicating 'Detected Tx Unit Hang...' and continues to generate the same error message.

Here is the produced error screen shot.
 
![virtualbox_rosewood_24_12_2016_18_48_45](https://cloud.githubusercontent.com/assets/22577647/21467170/9ac375a6-ca0a-11e6-959f-53f492b4ebd8.png)

**Comment by condor2** [comment]
What version of virtualbox?

**Comment by mrrabinhalder** [comment]
The version is 5.1.10.

**Comment by mrrabinhalder** [comment]
I upgraded to Virtualbox 5.1.12. It fixed the issue.

**Comment by condor2** [comment]
Yep, 5.1.10 was a version with problems :)
