### ISSUE TITLE
Add Nvidia DRM KMS support?

### ISSUE THREAD

**Issue by BooBerry** [deadhead420/arch-linux-anywhere#94]
This might (will) come in handy for us who use the proprietary Nvidia driver and wish to have DRM KMS support out of the box.

https://wiki.archlinux.org/index.php/NVIDIA#DRM_kernel_mode_setting
https://wiki.archlinux.org/index.php/Kernel_mode_setting

P.S. The Pacman hook included as well is likely a very good idea.

Thoughts?

**Comment by BooBerry** [comment]
I'm not sure if the older proprietary drivers support this as well, but I do know 364.12 and above do.

**Comment by deadhead420** [comment]
I've implimented this for the latest nvidia drivers. Pushed the code but have not tested yet. Creating a new ISO to test on my gtx 970 now.
