### ISSUE TITLE
Add option to update GPG keys

### ISSUE THREAD

**Issue by wizpig64** [deadhead420/arch-linux-anywhere#97]
I've been testing out arch linux via the -anywhere installer, version 2.2.3, and everything has been going great up to now. When I go through the installer and select a desktop/wm (not an issue without selecting a desktop), the installer fails due to some recent packages not matching up with the iso's outdated GPG keys. 

![archtest1](https://cloud.githubusercontent.com/assets/303302/21579518/2a49e9e0-cf69-11e6-85ec-90bd71379d17.PNG)

![archtest2](https://cloud.githubusercontent.com/assets/303302/21579519/2c77ec4e-cf69-11e6-9467-36a198db260a.PNG)

I fixed this by running `pacman-key --refresh-keys` before the installer. This took a few minutes to process, so I don't think it should be run by default as part of the installation. However, it would be nice to have the option to update the keys added to the start screen, which does already show the option to update the mirror list. It would certainly help out people like me who are new to arch, pacman, and key-signed packages, and save us from lots and lots of googling!

Thanks!

**Comment by deadhead420** [comment]
Thanks a lot for the report. Problem really is I need to do an update using the latest archiso. I've been busy testing 2.2.4 so I haven't looked at 2.2.3 at all in awhile. Haven't had a lot of time to work on scripting / testing / updating which is the reason the iso hasn't been updated in a few months. Now that I'm aware of this issue I will be doing another few tests and pushing out 2.2.4 in the next few hours granted no major issues arise. Keep an eye out for the updated ISO soon. Thanks again for making me aware of this issue.

**Comment by wizpig64** [comment]
No problem, looking forward to it. Thanks again for your work on the project, it's helped me a lot.

**Comment by deadhead420** [comment]
Not a problem! 2.2.4 has been released. Closing issue

**Comment by erriperry** [comment]
I just got this error while installing 2.2.5 in Virtualbox. After I ran `pacman-key --refresh-keys` it worked. So I guess this issue is not fixed.
